export type Industry = {
  id: string
  label: string
  shortLabel: string
  regime: 'current' | 'expanded'
  icon: string
  description: string
  obligations: string[]
  keyRisks: string[]
  austracRef: string
  packName: string
  color: string
}

export const industries: Industry[] = [
  {
    id: 'digital-currency-exchange',
    label: 'Digital Currency Exchange',
    shortLabel: 'Crypto / DCE',
    regime: 'current',
    icon: '₿',
    description: 'DCEs are required to register with AUSTRAC and implement full AML/CTF programs under the AML/CTF Act 2006.',
    obligations: ['AUSTRAC registration', 'KYC for all customers', 'TTR for cash ≥ $10,000', 'IFTI for international transfers', 'SMR for suspicious activity', 'Ongoing transaction monitoring'],
    keyRisks: ['Anonymity & pseudonymity', 'Cross-border exposure', 'Sanctions evasion', 'Structuring', 'High-risk jurisdictions'],
    austracRef: 'AML/CTF Act 2006 — Digital Currency Exchange Providers',
    packName: 'Crypto Pack',
    color: 'from-orange-500 to-amber-500',
  },
  {
    id: 'remittance-provider',
    label: 'Remittance Provider',
    shortLabel: 'Remittance',
    regime: 'current',
    icon: '🌏',
    description: 'Remittance providers transfer value on behalf of customers internationally and face IFTI reporting obligations.',
    obligations: ['AUSTRAC registration', 'Customer identification', 'IFTI IN & OUT reporting', 'Beneficiary screening', 'Agent network oversight', 'Ongoing CDD'],
    keyRisks: ['Third-party agents', 'High-volume low-value structuring', 'Hawala networks', 'PEP exposure', 'Sanctions'],
    austracRef: 'AML/CTF Act 2006 — Remittance Network Providers',
    packName: 'Remittance Pack',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'foreign-exchange',
    label: 'Foreign Exchange Provider',
    shortLabel: 'FX',
    regime: 'current',
    icon: '💱',
    description: 'FX businesses exchange currency and must identify customers, monitor transactions and report as required.',
    obligations: ['AUSTRAC registration', 'KYC at onboarding', 'TTR for cash ≥ $10,000', 'IFTI reporting', 'Ongoing monitoring', 'SMR filing'],
    keyRisks: ['Currency structuring', 'Trade-based money laundering', 'Bulk cash', 'High-risk customers'],
    austracRef: 'AML/CTF Act 2006 — Currency Exchange Providers',
    packName: 'FX Pack',
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: 'payment-service-provider',
    label: 'Payment Service Provider',
    shortLabel: 'PSP',
    regime: 'current',
    icon: '💳',
    description: 'PSPs facilitate payment flows and are reporting entities under the AML/CTF Act with broad monitoring obligations.',
    obligations: ['AUSTRAC registration', 'Merchant due diligence', 'Transaction monitoring', 'SMR reporting', 'IFTI for cross-border', 'Sanctions screening'],
    keyRisks: ['Merchant fraud', 'Card-not-present abuse', 'Velocity patterns', 'Cross-border exposure'],
    austracRef: 'AML/CTF Act 2006 — Payment Providers',
    packName: 'PSP Pack',
    color: 'from-purple-500 to-violet-500',
  },
  {
    id: 'lending-provider',
    label: 'Lending Provider',
    shortLabel: 'Lending',
    regime: 'current',
    icon: '🏦',
    description: 'Lending entities must verify borrower identity, assess source of funds, and monitor loan repayments for suspicious activity.',
    obligations: ['Customer identification', 'Source of funds verification', 'Ongoing CDD', 'SMR reporting', 'Beneficial ownership', 'Risk-based monitoring'],
    keyRisks: ['Loan-back schemes', 'Identity fraud', 'Shell company borrowers', 'Asset-based laundering'],
    austracRef: 'AML/CTF Act 2006 — Credit Providers',
    packName: 'Lending Pack',
    color: 'from-teal-500 to-cyan-600',
  },
  {
    id: 'real-estate',
    label: 'Real Estate Professional',
    shortLabel: 'Real Estate',
    regime: 'expanded',
    icon: '🏠',
    description: 'From 2026, real estate agents buying/selling on behalf of clients become reporting entities under the AML/CTF reforms.',
    obligations: ['Customer identification', 'Beneficial ownership checks', 'Source of funds verification', 'SMR reporting', 'Risk assessment', 'AML/CTF program required'],
    keyRisks: ['High-value property laundering', 'Shell company purchasers', 'PEP buyers', 'Offshore funds', 'Structuring below thresholds'],
    austracRef: 'AML/CTF Amendment Act 2024 — Tranche 2 Reform',
    packName: 'Real Estate Pack',
    color: 'from-rose-500 to-pink-500',
  },
  {
    id: 'conveyancer',
    label: 'Conveyancer',
    shortLabel: 'Conveyancer',
    regime: 'expanded',
    icon: '📋',
    description: 'Conveyancers handling property settlements will be captured under Tranche 2 reforms effective 2026.',
    obligations: ['Client identification', 'Property transaction monitoring', 'Source of funds checks', 'SMR reporting', 'Risk register maintenance', 'Training program'],
    keyRisks: ['Settlement fraud', 'Substitution of funds', 'Third-party payments', 'Identity fraud'],
    austracRef: 'AML/CTF Amendment Act 2024 — Tranche 2 Reform',
    packName: 'Conveyancer Pack',
    color: 'from-amber-500 to-orange-500',
  },
  {
    id: 'lawyer',
    label: 'Lawyer',
    shortLabel: 'Legal',
    regime: 'expanded',
    icon: '⚖️',
    description: 'Lawyers providing certain designated services — property, company formation, trust services — become reporting entities under Tranche 2.',
    obligations: ['Client due diligence', 'Matter risk assessment', 'Beneficial ownership verification', 'SMR for suspicious matters', 'AML/CTF program', 'Staff training'],
    keyRisks: ['Legal professional privilege tensions', 'Shell company formation', 'Trust and nominee structures', 'Property transactions'],
    austracRef: 'AML/CTF Amendment Act 2024 — Designated Non-Financial Businesses',
    packName: 'Legal Pack',
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 'accountant',
    label: 'Accountant',
    shortLabel: 'Accounting',
    regime: 'expanded',
    icon: '📊',
    description: 'Accountants providing certain services will be required to implement AML/CTF programs from 2026.',
    obligations: ['Client identification', 'Risk-based CDD', 'Beneficial ownership', 'Suspicious matter reporting', 'AML/CTF program', 'Record keeping'],
    keyRisks: ['Nominee directorship', 'Offshore structuring', 'Tax-linked laundering', 'Shell company administration'],
    austracRef: 'AML/CTF Amendment Act 2024 — Designated Non-Financial Businesses',
    packName: 'Accountant Pack',
    color: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'precious-metals',
    label: 'Precious Metal Dealer',
    shortLabel: 'Precious Metals',
    regime: 'expanded',
    icon: '🥇',
    description: 'Dealers in gold, silver, platinum and other precious metals are captured under Tranche 2 reforms.',
    obligations: ['Customer identification for cash ≥ $10K', 'TTR reporting', 'Suspicious matter reporting', 'Source of funds', 'Risk assessment', 'AML/CTF program'],
    keyRisks: ['Anonymous cash purchases', 'Bulk physical transfers', 'Refinery diversion', 'High-risk country sourcing'],
    austracRef: 'AML/CTF Amendment Act 2024 — Designated Non-Financial Businesses',
    packName: 'Precious Metals Pack',
    color: 'from-yellow-500 to-amber-400',
  },
]

export const getIndustry = (id: string) => industries.find(i => i.id === id)
