export type Industry = {
  id: string
  slug: string
  label: string
  shortLabel: string
  regime: 'current' | 'expanded'
  icon: string
  description: string
  overview: string
  obligations: string[]
  keyRisks: string[]
  risks: string[]
  cddRequirements: string[]
  monitoringRequirements: string[]
  reportingRequirements: {
    types: string[]
    details: string
  }
  howVerigoHelps: string[]
  austracRef: string
  packName: string
  color: string
}

export const industries: Industry[] = [
  {
    id: 'digital-currency-exchange',
    slug: 'digital-currency-exchange',
    label: 'Digital Currency Exchange',
    shortLabel: 'Crypto / DCE',
    regime: 'current',
    icon: '₿',
    description: 'DCEs are required to register with AUSTRAC and implement full AML/CTF programs under the AML/CTF Act 2006.',
    overview: 'Digital Currency Exchange providers are among the highest-risk reporting entities under Australia\'s AML/CTF regime. DCEs must register with AUSTRAC and operate a comprehensive AML/CTF program covering all aspects of customer onboarding, transaction monitoring, and regulatory reporting. The pseudonymous nature of cryptocurrency transactions creates heightened exposure to sanctions evasion, money laundering, and terrorism financing.',
    obligations: [
      'Register with AUSTRAC before providing DCE services',
      'Implement and maintain a Part A and Part B AML/CTF program',
      'Conduct KYC on all customers prior to providing services',
      'Lodge IFTI reports for international transfers of $10,000 AUD equivalent or more',
      'Lodge SMR reports for any transaction or activity suspected of being suspicious',
      'Lodge TTR reports for cash transactions of $10,000 AUD or more',
    ],
    keyRisks: [
      'High exposure to sanctions evasion via pseudonymous blockchain transactions',
      'Rapid movement of funds across borders complicating tracing',
      'Use of mixing and tumbling services to obscure transaction trails',
      'Customer use of privacy coins and anonymity-enhancing technologies',
    ],
    risks: [
      'High exposure to sanctions evasion via pseudonymous blockchain transactions',
      'Rapid movement of funds across borders complicating tracing',
      'Use of mixing and tumbling services to obscure transaction trails',
      'Customer use of privacy coins and anonymity-enhancing technologies',
    ],
    cddRequirements: [
      'Photo identification document and real-time biometric verification',
      'Source of funds declaration with supporting documentation for high-value customers',
      'Source of wealth verification for customers transacting above risk thresholds',
      'Residential address verification via utility bill or bank statement',
    ],
    monitoringRequirements: [
      'Real-time monitoring of all cryptocurrency transaction flows including deposit and withdrawal patterns',
      'Detection of structuring behaviour and smurfing patterns below reporting thresholds',
      'Wallet address screening against blockchain analytics databases for high-risk addresses',
    ],
    reportingRequirements: {
      types: ['SMR', 'IFTI', 'TTR'],
      details: 'DCEs must lodge SMRs within 3 business days of forming a suspicion, IFTIs within 10 business days of the transfer instruction, and TTRs within 10 business days of a threshold cash transaction.',
    },
    howVerigoHelps: [
      'Automated biometric KYC with document verification for fast, compliant customer onboarding',
      'Real-time sanctions and PEP screening against OFAC, UN, EU, DFAT, and UK HMT lists',
      'Pre-built cryptocurrency transaction monitoring rules including structuring detection and velocity checks',
      'IFTI, TTR, and SMR report templates pre-populated from transaction data with AUSTRAC validation',
      'Immutable audit trail for every customer interaction and compliance decision',
    ],
    austracRef: 'AML/CTF Act 2006 — Digital Currency Exchange Providers',
    packName: 'Crypto Pack',
    color: 'from-orange-500 to-amber-500',
  },
  {
    id: 'remittance-provider',
    slug: 'remittance-provider',
    label: 'Remittance Provider',
    shortLabel: 'Remittance',
    regime: 'current',
    icon: '🌏',
    description: 'Remittance providers transfer value on behalf of customers internationally and face IFTI reporting obligations.',
    overview: 'Remittance providers facilitate the international transfer of funds on behalf of customers and are subject to comprehensive obligations under the AML/CTF Act 2006. The remittance sector faces heightened risk from layering through multiple corridors, third-party agent networks, and the use of informal value transfer systems. Both the sender and beneficiary must be identified and verified for reportable transfers.',
    obligations: [
      'Register with AUSTRAC as a remittance network provider or independent remittance dealer',
      'Implement and maintain a full AML/CTF program',
      'Conduct KYC on both senders and beneficiaries for all transactions',
      'Lodge IFTI IN and IFTI OUT reports for international transfers of $10,000 AUD or more',
      'Lodge SMRs for any suspicious transaction or activity',
      'Lodge TTR reports for threshold cash transactions',
    ],
    keyRisks: [
      'Layering proceeds through multiple transfer corridors and jurisdictions',
      'Structuring transfers below reporting thresholds to avoid detection',
      'Use of nominees and third parties to disguise the true sender',
      'Connections to hawala and informal value transfer networks',
    ],
    risks: [
      'Layering proceeds through multiple transfer corridors and jurisdictions',
      'Structuring transfers below reporting thresholds to avoid detection',
      'Use of nominees and third parties to disguise the true sender',
      'Connections to hawala and informal value transfer networks',
    ],
    cddRequirements: [
      'Full KYC on senders including photo ID and address verification',
      'Beneficiary identification including name, account details, and destination country',
      'Purpose of transfer documentation for transactions above defined risk thresholds',
      'Enhanced due diligence for transfers to high-risk jurisdictions or PEP-connected beneficiaries',
    ],
    monitoringRequirements: [
      'Monitoring of transfer frequency, amounts, and destination country risk for individual customers',
      'Detection of structuring patterns where multiple transfers are made to avoid IFTI thresholds',
      'Corridor-level risk monitoring to identify unusual volume patterns to high-risk destinations',
    ],
    reportingRequirements: {
      types: ['IFTI', 'SMR', 'TTR'],
      details: 'Remittance providers must lodge IFTI IN reports within 10 business days of receiving an international transfer instruction and IFTI OUT reports within 10 business days of sending. SMRs must be lodged within 3 business days of forming a suspicion.',
    },
    howVerigoHelps: [
      'Automated KYC for both sender and beneficiary with pre-populated IFTI report fields',
      'Real-time sanctions screening for senders, beneficiaries, and destination jurisdictions',
      'Pre-built remittance monitoring rules including corridor risk scoring and structuring detection',
      'IFTI IN and IFTI OUT report templates with built-in AUSTRAC field validation',
      'Agent network oversight tools for remittance network providers with sub-agent compliance tracking',
    ],
    austracRef: 'AML/CTF Act 2006 — Remittance Network Providers',
    packName: 'Remittance Pack',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'foreign-exchange',
    slug: 'foreign-exchange',
    label: 'Foreign Exchange Provider',
    shortLabel: 'FX',
    regime: 'current',
    icon: '💱',
    description: 'FX businesses exchange currency and must identify customers, monitor transactions and report as required.',
    overview: 'Foreign exchange providers convert one currency into another for customers and are classified as reporting entities under the AML/CTF Act 2006. The FX sector faces unique risks from trade-based money laundering, bulk cash deposits, and cross-border payment manipulation. Every significant FX transaction must be screened, monitored, and potentially reported to AUSTRAC.',
    obligations: [
      'Register with AUSTRAC as a currency exchange provider',
      'Implement and maintain a Part A and Part B AML/CTF program',
      'Conduct KYC on all customers at the point of onboarding',
      'Lodge TTR reports for cash transactions of $10,000 AUD or more',
      'Lodge IFTI reports where the FX transaction involves an international element',
      'Lodge SMR reports for any suspicious activity or transaction',
    ],
    keyRisks: [
      'Currency structuring — breaking large exchanges into smaller transactions to avoid TTR thresholds',
      'Trade-based money laundering through over- or under-invoicing of currency conversions',
      'Bulk cash deposits connected to criminal proceeds requiring conversion',
      'High-risk customers or PEPs seeking to convert large amounts of foreign currency',
    ],
    risks: [
      'Currency structuring — breaking large exchanges into smaller transactions to avoid TTR thresholds',
      'Trade-based money laundering through over- or under-invoicing of currency conversions',
      'Bulk cash deposits connected to criminal proceeds requiring conversion',
      'High-risk customers or PEPs seeking to convert large amounts of foreign currency',
    ],
    cddRequirements: [
      'Photo identification document verification for all customers',
      'Address verification for customers transacting above defined thresholds',
      'Source of funds documentation for large or unusual conversion requests',
      'Enhanced due diligence for PEPs, high-risk jurisdiction customers, and large transaction customers',
    ],
    monitoringRequirements: [
      'Transaction monitoring for structuring patterns below the $10,000 TTR threshold',
      'Cross-border payment monitoring for transactions with an international element requiring IFTI reporting',
      'Customer-level velocity monitoring to detect unusual currency conversion frequency or volume',
    ],
    reportingRequirements: {
      types: ['TTR', 'IFTI', 'SMR'],
      details: 'FX providers must lodge TTR reports within 10 business days of a cash transaction at or above $10,000 AUD. IFTI reports are required where international transfer instructions are involved. SMRs must be lodged within 3 business days.',
    },
    howVerigoHelps: [
      'Automated customer onboarding with KYC verification and risk scoring tailored to FX transaction volumes',
      'Pre-built FX monitoring rules including TTR threshold alerts and structuring detection',
      'IFTI and TTR report templates pre-populated from transaction records with AUSTRAC validation',
      'Real-time PEP and sanctions screening at onboarding and for ongoing periodic review',
      'Audit trail documentation for every FX transaction, customer decision, and regulatory report',
    ],
    austracRef: 'AML/CTF Act 2006 — Currency Exchange Providers',
    packName: 'FX Pack',
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: 'payment-service-provider',
    slug: 'payment-service-provider',
    label: 'Payment Service Provider',
    shortLabel: 'PSP',
    regime: 'current',
    icon: '💳',
    description: 'PSPs facilitate payment flows and are reporting entities under the AML/CTF Act with broad monitoring obligations.',
    overview: 'Payment service providers that facilitate the transfer of funds between parties are reporting entities under the AML/CTF Act 2006. PSPs face unique obligations around merchant due diligence and end-user monitoring, as they operate as intermediaries across high volumes of transactions. Both the merchant and end-user must be subject to appropriate CDD and ongoing screening.',
    obligations: [
      'Register with AUSTRAC and maintain a full AML/CTF program',
      'Conduct due diligence on merchants at onboarding and on an ongoing basis',
      'Perform KYC on end-users engaging in reportable transactions',
      'Lodge SMR reports for suspicious transactions or merchant behaviour',
      'Lodge IFTI reports for international transfer instructions above the threshold',
      'Maintain sanctions screening across all merchants and high-value users',
    ],
    keyRisks: [
      'Merchant fraud — use of the PSP to process transactions linked to criminal activity',
      'Card-not-present abuse for online transactions enabling identity fraud',
      'Velocity pattern abuse — rapid small transactions designed to avoid detection',
      'Cross-border payment risk where merchant counterparties are in high-risk jurisdictions',
    ],
    risks: [
      'Merchant fraud — use of the PSP to process transactions linked to criminal activity',
      'Card-not-present abuse for online transactions enabling identity fraud',
      'Velocity pattern abuse — rapid small transactions designed to avoid detection',
      'Cross-border payment risk where merchant counterparties are in high-risk jurisdictions',
    ],
    cddRequirements: [
      'Business verification (KYB) for all merchants including beneficial ownership identification',
      'Individual KYC for merchants who are sole traders or principals of small businesses',
      'PEP and sanctions screening at merchant onboarding and ongoing periodic review',
      'Enhanced due diligence for high-risk merchant categories or abnormal transaction volumes',
    ],
    monitoringRequirements: [
      'Transaction-level monitoring for velocity patterns, unusual amounts, and high-risk merchant activity',
      'Merchant-level monitoring for changes in transaction profile indicating potential misuse',
      'IFTI monitoring for cross-border payment instructions above the reporting threshold',
    ],
    reportingRequirements: {
      types: ['SMR', 'IFTI', 'TTR'],
      details: 'PSPs must lodge SMRs within 3 business days of forming a suspicion about a transaction or customer. IFTI reports are required for international transfer instructions. TTRs apply to cash transactions at or above $10,000 AUD.',
    },
    howVerigoHelps: [
      'KYB workflows for merchant onboarding including business verification and beneficial ownership mapping',
      'Automated PEP and sanctions screening for merchants at onboarding and on periodic renewal',
      'Pre-built transaction monitoring rules for PSP-specific risk including velocity and cross-border patterns',
      'Case management workflows linking transaction alerts to investigation and SMR preparation',
      'Full audit trail for every merchant decision, transaction alert, and AUSTRAC submission',
    ],
    austracRef: 'AML/CTF Act 2006 — Payment Providers',
    packName: 'PSP Pack',
    color: 'from-purple-500 to-violet-500',
  },
  {
    id: 'real-estate',
    slug: 'real-estate',
    label: 'Real Estate Professional',
    shortLabel: 'Real Estate',
    regime: 'expanded',
    icon: '🏠',
    description: 'From 2026, real estate agents buying/selling on behalf of clients become reporting entities under the AML/CTF reforms.',
    overview: 'Real estate professionals who buy or sell real property on behalf of clients will become reporting entities under the AML/CTF Amendment Act 2024 from 2026. Real estate is a well-documented vehicle for money laundering, with high-value all-cash property transactions, offshore buyer structures, and complex trust and corporate ownership used to conceal the origins of illicit funds. The Australian property market has been identified as a high-risk sector by both AUSTRAC and international assessors.',
    obligations: [
      'Enrol with AUSTRAC and implement a full AML/CTF program before providing designated services',
      'Conduct customer due diligence on both buyers and sellers at the commencement of the business relationship',
      'Verify the source of funds to be used in the property transaction',
      'Identify beneficial owners of corporate or trust purchasers',
      'Lodge SMR reports for any suspicious activity related to a property transaction',
      'Maintain records of all CDD conducted for a minimum of 7 years',
    ],
    keyRisks: [
      'Property used to launder proceeds of serious crime through all-cash or over-valued purchases',
      'Offshore buyers using complex company and trust structures to obscure true ownership',
      'All-cash transactions bypassing standard financial institution due diligence',
      'PEPs and their associates purchasing high-value property using nominee structures',
    ],
    risks: [
      'Property used to launder proceeds of serious crime through all-cash or over-valued purchases',
      'Offshore buyers using complex company and trust structures to obscure true ownership',
      'All-cash transactions bypassing standard financial institution due diligence',
      'PEPs and their associates purchasing high-value property using nominee structures',
    ],
    cddRequirements: [
      'Identity verification of both the buyer and seller parties with photo ID and address confirmation',
      'Source of funds documentation from the buyer prior to or at settlement',
      'Ultimate beneficial owner identification for any corporate or trust purchaser',
      'PEP and sanctions screening of all parties to the transaction',
    ],
    monitoringRequirements: [
      'Client-level monitoring across multiple transactions to identify patterns indicative of property-based laundering',
      'Source of funds verification review at key stages of the property transaction lifecycle',
      'Post-transaction review for any indicators identified after settlement that may require SMR filing',
    ],
    reportingRequirements: {
      types: ['SMR'],
      details: 'Real estate professionals must lodge SMR reports with AUSTRAC within 3 business days of forming a suspicion about a transaction, client, or property transaction. There is no obligation to report the existence of an SMR to the client.',
    },
    howVerigoHelps: [
      'End-to-end CDD workflows for both buyer and seller with guided identity verification and document collection',
      'Beneficial ownership mapping tool for corporate and trust purchasers with UBO identification',
      'Source of funds verification module with document upload and review capability',
      'PEP and sanctions screening integrated into the buyer onboarding workflow',
      'SMR preparation templates and case management tools for investigating suspicious transactions',
    ],
    austracRef: 'AML/CTF Amendment Act 2024 — Tranche 2 Reform',
    packName: 'Real Estate Pack',
    color: 'from-rose-500 to-pink-500',
  },
  {
    id: 'conveyancer',
    slug: 'conveyancer',
    label: 'Conveyancer',
    shortLabel: 'Conveyancer',
    regime: 'expanded',
    icon: '📋',
    description: 'Conveyancers handling property settlements will be captured under Tranche 2 reforms effective 2026.',
    overview: 'Conveyancers who facilitate the settlement of property transactions will be captured under the AML/CTF Amendment Act 2024 from 2026. The conveyancing stage of a property transaction is particularly vulnerable to money laundering because large sums of money change hands at settlement. Conveyancers must implement CDD procedures, verify the source of settlement funds, and report suspicious activity to AUSTRAC.',
    obligations: [
      'Enrol with AUSTRAC and implement a full AML/CTF program',
      'Conduct CDD on clients at the commencement of the conveyancing matter',
      'Verify the source of funds to be used at property settlement',
      'Conduct ongoing monitoring throughout the matter lifecycle',
      'Lodge SMR reports for any suspicious activity identified',
      'Maintain records of all CDD and transaction documentation for 7 years',
    ],
    keyRisks: [
      'Settlement fraud involving substitution of legitimate funds at the last stage of the transaction',
      'Third-party payments where funds at settlement come from an undisclosed source',
      'Identity fraud — use of fraudulent identity documents to impersonate buyers or sellers',
      'Large cash contributions to settlement proceeds that cannot be traced to legitimate sources',
    ],
    risks: [
      'Settlement fraud involving substitution of legitimate funds at the last stage of the transaction',
      'Third-party payments where funds at settlement come from an undisclosed source',
      'Identity fraud — use of fraudulent identity documents to impersonate buyers or sellers',
      'Large cash contributions to settlement proceeds that cannot be traced to legitimate sources',
    ],
    cddRequirements: [
      'Identity verification of all clients using government-issued photo identification',
      'Source of funds verification for the settlement amount with supporting bank or financial records',
      'Beneficial ownership identification where the client is acting on behalf of a company or trust',
      'PEP and sanctions screening of all parties at matter commencement',
    ],
    monitoringRequirements: [
      'Transaction monitoring across the matter lifecycle for changes in settlement amounts or payment sources',
      'Review of source of funds documentation prior to settlement for completeness and plausibility',
      'Post-settlement review for any indicators that may require retrospective SMR filing',
    ],
    reportingRequirements: {
      types: ['SMR'],
      details: 'Conveyancers must lodge SMR reports within 3 business days of forming a suspicion about a client, transaction, or settlement amount. There is no obligation to inform the client that an SMR has been lodged.',
    },
    howVerigoHelps: [
      'Client onboarding workflows with integrated KYC and document collection for conveyancing matters',
      'Source of funds verification module with document upload, review, and approval workflow',
      'PEP and sanctions screening at matter commencement and on periodic review',
      'Case management tools for investigating red flags and documenting SMR decisions',
      'Pre-built AML/CTF program template for conveyancers aligned to the Tranche 2 obligations',
    ],
    austracRef: 'AML/CTF Amendment Act 2024 — Tranche 2 Reform',
    packName: 'Conveyancer Pack',
    color: 'from-amber-500 to-orange-500',
  },
  {
    id: 'law-firm',
    slug: 'law-firm',
    label: 'Law Firm',
    shortLabel: 'Legal',
    regime: 'expanded',
    icon: '⚖️',
    description: 'Law firms providing certain designated services — property, company formation, trust services — become reporting entities under Tranche 2.',
    overview: 'Law firms that provide designated services including buying and selling real property on behalf of clients, managing client funds, forming or operating companies and trusts, and other specified legal services will become reporting entities under the AML/CTF Amendment Act 2024. The legal profession is considered a high-risk sector due to the use of trust accounts, professional privilege, and the range of complex legal structures that can be used to conceal beneficial ownership.',
    obligations: [
      'Enrol with AUSTRAC and implement a full AML/CTF program for designated legal services',
      'Conduct client due diligence at the commencement of each matter involving a designated service',
      'Verify the beneficial ownership and control of corporate or trust clients',
      'Monitor client trust account transactions for suspicious patterns',
      'Lodge SMR reports for suspicious activity identified in connection with designated services',
      'Train all staff providing designated services in AML/CTF obligations',
    ],
    keyRisks: [
      'Shell company and complex trust formation used to layer and conceal beneficial ownership',
      'Client trust account misuse to layer criminal proceeds through the firm\'s accounts',
      'Legal professional privilege creating compliance tension around information disclosure',
      'Property transactions used as the vehicle for large-scale money laundering',
    ],
    risks: [
      'Shell company and complex trust formation used to layer and conceal beneficial ownership',
      'Client trust account misuse to layer criminal proceeds through the firm\'s accounts',
      'Legal professional privilege creating compliance tension around information disclosure',
      'Property transactions used as the vehicle for large-scale money laundering',
    ],
    cddRequirements: [
      'Full identity verification of clients and their authorised representatives at matter inception',
      'Beneficial ownership and control structure verification for all corporate and trust clients',
      'Source of funds verification for client monies received and held in trust',
      'PEP and sanctions screening of all clients at onboarding and on periodic renewal',
    ],
    monitoringRequirements: [
      'Client trust account transaction monitoring for unusual patterns, large deposits, or unexplained receipts',
      'Matter-level monitoring for changes in the nature or value of the transaction that may affect risk',
      'Ongoing periodic review of client risk ratings and CDD records across the matter lifecycle',
    ],
    reportingRequirements: {
      types: ['SMR'],
      details: 'Law firms must lodge SMR reports within 3 business days of forming a suspicion in connection with a designated service. The legal professional privilege exception applies narrowly and does not exempt lawyers from SMR obligations across all circumstances.',
    },
    howVerigoHelps: [
      'Matter-based CDD workflows integrating client onboarding, identity verification, and risk assessment',
      'Beneficial ownership mapping for complex corporate and trust structures with UBO identification',
      'Client trust account monitoring with configurable rules for unusual transaction detection',
      'SMR preparation and case management tools for MLRO review and regulatory reporting',
      'AML/CTF program template for law firms with matter risk assessment and staff training tracking',
    ],
    austracRef: 'AML/CTF Amendment Act 2024 — Designated Non-Financial Businesses',
    packName: 'Legal Pack',
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 'accounting-firm',
    slug: 'accounting-firm',
    label: 'Accounting Firm',
    shortLabel: 'Accounting',
    regime: 'expanded',
    icon: '📊',
    description: 'Accounting firms providing certain services will be required to implement AML/CTF programs from 2026.',
    overview: 'Accounting firms that provide designated services including company and trust formation, acting as nominee directors, managing client funds, and providing tax-related services will become reporting entities under the AML/CTF Amendment Act 2024 from 2026. Accountants occupy a unique position in the financial crime ecosystem as they often facilitate the structures that enable tax evasion and money laundering, and have access to detailed financial information that can be misused.',
    obligations: [
      'Enrol with AUSTRAC and implement a full AML/CTF program for designated accounting services',
      'Conduct client due diligence on all clients receiving designated services',
      'Identify the beneficial ownership of corporate and trust clients',
      'Lodge SMR reports for suspicious activity connected to designated services',
      'Maintain records of all CDD, transactions, and compliance decisions for 7 years',
      'Conduct ongoing periodic review of client risk ratings and CDD documentation',
    ],
    keyRisks: [
      'Tax evasion facilitation through offshore structuring and opaque ownership arrangements',
      'Shell company administration enabling clients to conceal assets and beneficial ownership',
      'Nominee director and shareholder arrangements used to distance individuals from entities',
      'Client fund management creating exposure to layering through accounting trust accounts',
    ],
    risks: [
      'Tax evasion facilitation through offshore structuring and opaque ownership arrangements',
      'Shell company administration enabling clients to conceal assets and beneficial ownership',
      'Nominee director and shareholder arrangements used to distance individuals from entities',
      'Client fund management creating exposure to layering through accounting trust accounts',
    ],
    cddRequirements: [
      'Identity verification of all clients and their authorised representatives',
      'Beneficial ownership identification for all corporate and trust clients receiving designated services',
      'Source of funds or wealth verification for clients seeking to move or invest significant funds',
      'PEP and sanctions screening of clients and beneficial owners at onboarding and ongoing review',
    ],
    monitoringRequirements: [
      'Client-level monitoring for changes in the nature of services requested that may indicate elevated risk',
      'Review of corporate and trust structures at periodic intervals for changes in beneficial ownership',
      'Monitoring for indicators of tax evasion facilitation or offshore structuring for illicit purposes',
    ],
    reportingRequirements: {
      types: ['SMR'],
      details: 'Accounting firms must lodge SMR reports within 3 business days of forming a suspicion in connection with a designated service. The obligation to report is not negated by client confidentiality — there is a specific carve-out in accounting professional conduct rules for AML/CTF obligations.',
    },
    howVerigoHelps: [
      'Client onboarding workflows with integrated identity verification and risk-based CDD for accounting services',
      'Beneficial ownership mapping for complex corporate structures and multi-layered trust arrangements',
      'Ongoing periodic review scheduler to ensure client CDD remains current and risk ratings are reviewed',
      'SMR case management and preparation tools for MLRO review before AUSTRAC lodgement',
      'AML/CTF program template for accounting firms with designated service identification and staff training log',
    ],
    austracRef: 'AML/CTF Amendment Act 2024 — Designated Non-Financial Businesses',
    packName: 'Accountant Pack',
    color: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'precious-metals',
    slug: 'precious-metals',
    label: 'Precious Metal Dealer',
    shortLabel: 'Precious Metals',
    regime: 'expanded',
    icon: '🥇',
    description: 'Dealers in gold, silver, platinum and other precious metals are captured under Tranche 2 reforms.',
    overview: 'Dealers in precious metals including gold, silver, platinum, and gemstones will be captured as reporting entities under the AML/CTF Amendment Act 2024 from 2026. Physical precious metals are an attractive vehicle for money laundering because they are portable, high-value, and have historically been purchased with cash in ways that bypass financial system scrutiny. The TTR threshold of $10,000 applies to cash transactions in this sector.',
    obligations: [
      'Enrol with AUSTRAC and implement a full AML/CTF program',
      'Conduct CDD on customers purchasing precious metals in cash transactions at or above $10,000 AUD',
      'Lodge TTR reports for cash transactions at or above $10,000 AUD',
      'Lodge SMR reports for any suspicious purchase, sale, or exchange activity',
      'Maintain records of all CDD and transaction documentation',
      'Conduct a risk assessment of the business and implement proportionate controls',
    ],
    keyRisks: [
      'Anonymous cash purchases of high-value physical assets enabling currency to be converted without scrutiny',
      'Bulk physical precious metal transfers used to move value across borders outside the financial system',
      'Refinery diversion schemes where stolen or illicitly sourced precious metals enter the legitimate market',
      'Purchases sourced from high-risk countries or suppliers connected to conflict minerals',
    ],
    risks: [
      'Anonymous cash purchases of high-value physical assets enabling currency to be converted without scrutiny',
      'Bulk physical precious metal transfers used to move value across borders outside the financial system',
      'Refinery diversion schemes where stolen or illicitly sourced precious metals enter the legitimate market',
      'Purchases sourced from high-risk countries or suppliers connected to conflict minerals',
    ],
    cddRequirements: [
      'Identity verification with photo identification for all customers making cash transactions at or above $10,000',
      'Source of funds verification for high-value cash purchases with documentation of legitimate origin',
      'PEP and sanctions screening for customers making purchases above defined risk thresholds',
      'Enhanced due diligence for customers purchasing in unusual quantities, frequencies, or with unusual payment methods',
    ],
    monitoringRequirements: [
      'Transaction monitoring for structuring behaviour — multiple purchases below $10,000 to avoid TTR obligations',
      'Customer-level monitoring for frequency and pattern of precious metal purchases and sales',
      'Supplier due diligence monitoring to screen against conflict mineral and sanctions databases',
    ],
    reportingRequirements: {
      types: ['TTR', 'SMR'],
      details: 'Precious metal dealers must lodge TTR reports within 10 business days of a cash transaction at or above $10,000 AUD. SMR reports must be lodged within 3 business days of forming a suspicion about a transaction or customer.',
    },
    howVerigoHelps: [
      'Customer onboarding and KYC workflows calibrated for precious metal transaction thresholds and risk',
      'TTR report templates pre-populated from transaction records with AUSTRAC field validation',
      'Automated structuring detection alerts for customers making multiple transactions below TTR thresholds',
      'PEP and sanctions screening integrated into the point-of-sale customer identification workflow',
      'AML/CTF program template for precious metal dealers with transaction risk assessment and staff training log',
    ],
    austracRef: 'AML/CTF Amendment Act 2024 — Designated Non-Financial Businesses',
    packName: 'Precious Metals Pack',
    color: 'from-yellow-500 to-amber-400',
  },
  {
    id: 'reporting-group',
    slug: 'reporting-group',
    label: 'Reporting Group',
    shortLabel: 'Reporting Group',
    regime: 'current',
    icon: '🏢',
    description: 'Multi-entity compliance groups can establish a reporting group to consolidate compliance operations and share customer data across related entities.',
    overview: 'A reporting group is an arrangement under the AML/CTF Act 2006 that allows two or more related reporting entities to operate a single AML/CTF program and share customer information and compliance infrastructure. Reporting groups are common among diversified financial services organisations that operate multiple regulated businesses under a common parent. The group structure enables consolidated AUSTRAC reporting, shared risk assessments, and centralised compliance oversight.',
    obligations: [
      'Apply to AUSTRAC for authorisation to operate as a reporting group',
      'Maintain a group-wide AML/CTF program covering all member entities',
      'Conduct a consolidated risk assessment addressing risks across all group entities',
      'Ensure each member entity maintains its own AUSTRAC enrolment and reporting obligations',
      'Share customer identification and transaction records across group entities as permitted',
      'Lodge consolidated or entity-level AUSTRAC reports as required by group structure',
    ],
    keyRisks: [
      'Inconsistent compliance standards across group entities creating regulatory exposure for the group',
      'Customer information sharing without adequate data governance and access controls',
      'Entity-level compliance gaps hidden by a group-level view that masks individual weaknesses',
      'Group-wide policies that fail to account for the different obligation profiles of individual entities',
    ],
    risks: [
      'Inconsistent compliance standards across group entities creating regulatory exposure for the group',
      'Customer information sharing without adequate data governance and access controls',
      'Entity-level compliance gaps hidden by a group-level view that masks individual weaknesses',
      'Group-wide policies that fail to account for the different obligation profiles of individual entities',
    ],
    cddRequirements: [
      'Group-level shared customer master records enabling CDD conducted once to satisfy multiple entities',
      'Entity-specific CDD overlays where the individual entity\'s obligations require additional verification',
      'Consolidated beneficial ownership records across all group entities and relationships',
      'Group-wide PEP and sanctions screening with results shared and accessible to all member entities',
    ],
    monitoringRequirements: [
      'Consolidated transaction monitoring across all group entities to identify group-level patterns',
      'Entity-level monitoring overlays to address specific risk profiles of individual regulated businesses',
      'Group-level reporting dashboard providing real-time compliance status across all entities',
    ],
    reportingRequirements: {
      types: ['SMR', 'IFTI', 'TTR'],
      details: 'Reporting group entities may lodge reports individually or under group-level arrangements depending on their AUSTRAC authorisation. Each entity remains individually responsible for lodging required reports on time.',
    },
    howVerigoHelps: [
      'Multi-entity group dashboard providing consolidated compliance status and reporting across all members',
      'Shared customer master records enabling CDD conducted once to be relied upon across group entities',
      'Group-level AML/CTF program management with entity-specific compliance overlays',
      'Consolidated AUSTRAC reporting with the ability to prepare and lodge reports per entity',
      'Group-wide audit trail and access controls ensuring appropriate data governance across the group',
    ],
    austracRef: 'AML/CTF Act 2006 — Reporting Groups',
    packName: 'Reporting Group Pack',
    color: 'from-teal-500 to-cyan-600',
  },
]

export const getIndustry = (id: string) => industries.find(i => i.id === id)
