from app.templates.risk.base import LibraryFactor, RiskLibrary


def get_library() -> RiskLibrary:
    return RiskLibrary(
        industry="banking",
        description="Authorised deposit-taking institution (ADI) / banking — Tranche 1.",
        category_weights={
            "customer": 0.25,
            "product": 0.20,
            "service": 0.10,
            "geographic": 0.15,
            "channel": 0.05,
            "transaction": 0.20,
            "regulatory": 0.05,
        },
        factors=[
            LibraryFactor(
                ref="CUST-001",
                category_type="customer",
                name="Politically Exposed Persons (PEPs)",
                description="Domestic/foreign PEPs and their associates holding accounts or credit facilities.",
                suggested_likelihood=2,
                suggested_consequence=5,
                rationale="PEPs represent elevated corruption and bribery risk; banks are common PEP banking channels.",
                mitigation_examples=[
                    "Senior management approval for PEP relationships",
                    "Source-of-wealth documentation",
                    "Annual PEP review",
                ],
            ),
            LibraryFactor(
                ref="CUST-002",
                category_type="customer",
                name="Non-resident / offshore account holders",
                description="Non-Australian residents holding accounts or accessing banking services remotely.",
                suggested_likelihood=3,
                suggested_consequence=3,
                rationale="Non-residents present higher CDD challenges and jurisdictional risk.",
                mitigation_examples=[
                    "Enhanced CDD for non-resident accounts",
                    "FATCA/CRS compliance for reportable accounts",
                ],
            ),
            LibraryFactor(
                ref="CUST-003",
                category_type="customer",
                name="High-risk business sectors (MSBs, legal, real estate)",
                description="Customers operating in sectors with higher inherent ML risk (e.g. money service businesses).",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="MSB and professional services accounts are used to layer proceeds.",
                mitigation_examples=[
                    "Sector-specific EDD procedures",
                    "Periodic review of business activity against expected profile",
                ],
            ),
            LibraryFactor(
                ref="PROD-001",
                category_type="product",
                name="Correspondent banking relationships",
                description="Maintaining correspondent accounts for foreign banks.",
                suggested_likelihood=3,
                suggested_consequence=5,
                rationale="Correspondent banking is a primary mechanism for cross-border ML; respondent bank's AML quality is critical.",
                mitigation_examples=[
                    "Annual correspondent bank risk assessment",
                    "No relationships with shell banks",
                    "Enhanced due diligence on respondent AML programs",
                ],
            ),
            LibraryFactor(
                ref="PROD-002",
                category_type="product",
                name="Trade finance / letters of credit",
                description="Documentary credit facilities that may be used for trade-based ML (TBML).",
                suggested_likelihood=2,
                suggested_consequence=4,
                rationale="TBML is a sophisticated and growing technique used to move value across borders.",
                mitigation_examples=[
                    "Dual-control review of trade documents",
                    "Sanctions screening on all trade counterparties",
                ],
            ),
            LibraryFactor(
                ref="GEO-001",
                category_type="geographic",
                name="Transactions to/from sanctioned jurisdictions",
                description="Wire transfers or other payments involving OFAC/UN sanctioned countries.",
                suggested_likelihood=2,
                suggested_consequence=5,
                rationale="Sanctions breaches carry severe regulatory and reputational consequences.",
                mitigation_examples=[
                    "Real-time SWIFT sanctions screening",
                    "Automatic block on sanctioned jurisdiction transactions",
                ],
            ),
            LibraryFactor(
                ref="TXN-001",
                category_type="transaction",
                name="Cash Threshold Reports (CTRs / TTRs)",
                description="Risk of missed or late Threshold Transaction Reports for cash transactions ≥$10,000.",
                suggested_likelihood=2,
                suggested_consequence=4,
                rationale="Mandatory TTR obligation; non-reporting is a strict liability offence.",
                mitigation_examples=[
                    "Automated TTR generation at teller and ATM level",
                    "Same-day TTR submission to AUSTRAC",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="TXN-002",
                category_type="transaction",
                name="Structuring / smurfing",
                description="Multiple transactions structured to remain below the $10,000 TTR threshold.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Structuring is a criminal offence and common ML technique targeting bank branches.",
                mitigation_examples=[
                    "Rolling 30-day cumulative cash monitoring",
                    "Branch staff training on structuring red flags",
                ],
            ),
            LibraryFactor(
                ref="TXN-003",
                category_type="transaction",
                name="International Fund Transfer Instructions (IFTI)",
                description="Failure to report IFTIs to AUSTRAC within 10 business days.",
                suggested_likelihood=2,
                suggested_consequence=4,
                rationale="Mandatory Tranche 1 obligation for banks processing international wire transfers.",
                mitigation_examples=[
                    "Automated IFTI submission integrated with wire transfer system",
                    "Daily IFTI exception report",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="REG-001",
                category_type="regulatory",
                name="Independent AML/CTF audit non-compliance",
                description="Failure to conduct required independent review of AML/CTF program.",
                suggested_likelihood=1,
                suggested_consequence=3,
                rationale="AUSTRAC requires independent review; gaps identified in audits must be remediated.",
                mitigation_examples=[
                    "Annual independent audit scheduled",
                    "Audit findings tracked to closure in control register",
                ],
            ),
        ],
    )
