from app.templates.risk.base import LibraryFactor, RiskLibrary


def get_library() -> RiskLibrary:
    return RiskLibrary(
        industry="fintech",
        description="Fintech / neobank / payment service provider — Tranche 1.",
        category_weights={
            "customer": 0.20,
            "product": 0.20,
            "service": 0.10,
            "geographic": 0.15,
            "channel": 0.15,
            "transaction": 0.15,
            "regulatory": 0.05,
        },
        factors=[
            LibraryFactor(
                ref="CUST-001",
                category_type="customer",
                name="Rapid digital onboarding — identity fraud risk",
                description="Customers onboarded at high velocity via digital channels with limited friction.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Frictionless onboarding is a key fintech selling point but creates identity verification risk.",
                mitigation_examples=[
                    "Biometric liveness check at onboarding",
                    "Device fingerprinting",
                    "Velocity limits on new account creation",
                ],
            ),
            LibraryFactor(
                ref="CUST-002",
                category_type="customer",
                name="Synthetic identity customers",
                description="Use of fabricated or combination identities to open accounts.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Synthetic identities are increasingly used to bypass standard KYC checks.",
                mitigation_examples=[
                    "Credit bureau cross-reference on onboarding",
                    "Document authenticity verification (OCR + liveness)",
                ],
            ),
            LibraryFactor(
                ref="PROD-001",
                category_type="product",
                name="Buy-Now-Pay-Later (BNPL) facilities",
                description="Instant credit facilities extended without full credit assessment.",
                suggested_likelihood=2,
                suggested_consequence=3,
                rationale="BNPL can be used to purchase goods for resale (ML) or access credit fraudulently.",
                mitigation_examples=[
                    "Transaction monitoring on BNPL utilisation patterns",
                    "Merchant category controls",
                ],
            ),
            LibraryFactor(
                ref="PROD-002",
                category_type="product",
                name="Embedded payments / API banking",
                description="Payment functionality embedded in third-party platforms via API.",
                suggested_likelihood=3,
                suggested_consequence=3,
                rationale="Embedded payments reduce visibility into end-user transactions and context.",
                mitigation_examples=[
                    "API partner due diligence",
                    "Contractual AML obligations on API partners",
                    "Aggregated transaction monitoring",
                ],
            ),
            LibraryFactor(
                ref="GEO-001",
                category_type="geographic",
                name="Cross-border payment corridors",
                description="International payment corridors to higher-risk jurisdictions.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Fintechs offering international payments inherit the same corridor risk as remittance providers.",
                mitigation_examples=[
                    "Corridor-specific risk ratings",
                    "Enhanced monitoring on high-risk corridors",
                    "Travel Rule compliance for VASP corridors",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="CHAN-001",
                category_type="channel",
                name="100% digital — no face-to-face",
                description="No physical presence for verification; all interactions are remote/digital.",
                suggested_likelihood=3,
                suggested_consequence=3,
                rationale="Digital-only channels are higher risk for impersonation and synthetic identities.",
                mitigation_examples=[
                    "Video KYC for higher-risk customers",
                    "Step-up authentication for large transactions",
                ],
            ),
            LibraryFactor(
                ref="TXN-001",
                category_type="transaction",
                name="Account-to-account rapid transfers",
                description="Rapid movement of funds between linked accounts with minimal dwell time.",
                suggested_likelihood=3,
                suggested_consequence=3,
                rationale="Fast A2A transfers facilitate layering in the absence of hold periods.",
                mitigation_examples=[
                    "Dwell-time alerts for funds in transit <1 hour",
                    "New payee limits for first 30 days",
                ],
            ),
            LibraryFactor(
                ref="REG-001",
                category_type="regulatory",
                name="AUSTRAC enrolment and program maintenance",
                description="Risk of operating without AUSTRAC enrolment or with an outdated AML/CTF program.",
                suggested_likelihood=1,
                suggested_consequence=4,
                rationale="Fintech growth and product evolution can outpace AML program updates.",
                mitigation_examples=[
                    "Trigger program review on new product launch",
                    "Quarterly regulatory change monitoring",
                ],
            ),
        ],
    )
