from app.templates.risk.base import LibraryFactor, RiskLibrary


def get_library() -> RiskLibrary:
    return RiskLibrary(
        industry="remittance",
        description="International remittance / money transfer — Tranche 1 reporting entity.",
        category_weights={
            "customer": 0.25,
            "product": 0.15,
            "service": 0.10,
            "geographic": 0.20,
            "channel": 0.10,
            "transaction": 0.15,
            "regulatory": 0.05,
        },
        factors=[
            # ── Customer ──────────────────────────────────────────────────────
            LibraryFactor(
                ref="CUST-001",
                category_type="customer",
                name="High-volume cash customers",
                description="Customers who regularly transact in cash without clear economic rationale.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Cash transactions obscure origin of funds and are a primary ML vector for remittance businesses.",
                mitigation_examples=[
                    "Source-of-funds declaration for cash >$2,000",
                    "Enhanced CDD for regular cash customers",
                ],
            ),
            LibraryFactor(
                ref="CUST-002",
                category_type="customer",
                name="Politically Exposed Persons (PEPs)",
                description="Customers who are foreign or domestic PEPs or immediate family/associates.",
                suggested_likelihood=2,
                suggested_consequence=5,
                rationale="PEPs represent elevated risk of bribery, corruption, and misappropriation of public funds.",
                mitigation_examples=[
                    "Mandatory MLRO approval for PEP onboarding",
                    "Enhanced CDD and source-of-wealth documentation",
                    "Annual PEP re-screening",
                ],
            ),
            LibraryFactor(
                ref="CUST-003",
                category_type="customer",
                name="Anonymous or unverified senders",
                description="Transactions initiated by customers with incomplete or unverifiable identity documents.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Anonymous remittances are a known smuggling and ML conduit.",
                mitigation_examples=[
                    "Mandatory ID verification at onboarding",
                    "Reject transactions from unverified customers",
                ],
            ),
            LibraryFactor(
                ref="CUST-004",
                category_type="customer",
                name="Non-resident / offshore customers",
                description="Customers residing outside Australia with beneficiaries in high-risk jurisdictions.",
                suggested_likelihood=3,
                suggested_consequence=3,
                rationale="Cross-border remittances add complexity to CDD and beneficial ownership.",
                mitigation_examples=[
                    "Additional verification for non-residents",
                    "Restrict corridors to FATF-compliant jurisdictions",
                ],
            ),
            # ── Product/Service ───────────────────────────────────────────────
            LibraryFactor(
                ref="PROD-001",
                category_type="product",
                name="International wire transfers",
                description="Outgoing/incoming wire transfers to/from overseas accounts.",
                suggested_likelihood=4,
                suggested_consequence=4,
                rationale="Core product; primary ML/TF vector. High inherent risk by nature of product.",
                mitigation_examples=[
                    "Travel Rule compliance for transfers ≥$1,000",
                    "Real-time sanctions screening on all wires",
                    "TTR for cash transactions ≥$10,000",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="PROD-002",
                category_type="product",
                name="Nested remittance / agent network",
                description="Use of sub-agents or third-party agents to deliver remittance services.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Agent networks can obscure the ultimate sender/beneficiary and create compliance gaps.",
                mitigation_examples=[
                    "Agent due diligence and AML training requirements",
                    "Contractual AML obligations on agents",
                    "Regular agent audits",
                ],
            ),
            # ── Geographic ────────────────────────────────────────────────────
            LibraryFactor(
                ref="GEO-001",
                category_type="geographic",
                name="High-risk destination corridors",
                description="Remittance corridors to FATF grey/black-listed or sanctions-affected jurisdictions.",
                suggested_likelihood=4,
                suggested_consequence=5,
                rationale="Transfers to high-risk jurisdictions carry significantly elevated TF and ML risk.",
                mitigation_examples=[
                    "Block transfers to sanctioned jurisdictions",
                    "Enhanced due diligence for grey-listed corridors",
                    "Transaction monitoring with lower thresholds",
                ],
            ),
            LibraryFactor(
                ref="GEO-002",
                category_type="geographic",
                name="Conflict-affected regions",
                description="Remittances directed to regions experiencing active armed conflict.",
                suggested_likelihood=3,
                suggested_consequence=5,
                rationale="Conflict zones increase TF risk; funds may support non-state armed groups.",
                mitigation_examples=[
                    "Corridor-specific risk assessment",
                    "MLRO approval for conflict-zone transactions",
                ],
            ),
            # ── Channel ───────────────────────────────────────────────────────
            LibraryFactor(
                ref="CHAN-001",
                category_type="channel",
                name="Digital / mobile app channel",
                description="Customers onboarded and transacting entirely online without face-to-face verification.",
                suggested_likelihood=3,
                suggested_consequence=3,
                rationale="Digital channels reduce ability to verify identity in-person; higher impersonation risk.",
                mitigation_examples=[
                    "Digital ID verification (e.g. biometric liveness check)",
                    "Device fingerprinting and fraud analytics",
                ],
            ),
            LibraryFactor(
                ref="CHAN-002",
                category_type="channel",
                name="Retail / over-the-counter cash intake",
                description="In-person cash intake at retail or agent locations.",
                suggested_likelihood=4,
                suggested_consequence=4,
                rationale="OTC cash is the highest-risk intake channel for remittance businesses.",
                mitigation_examples=[
                    "CCTV at all cash intake points",
                    "Staff AML training for structured transactions",
                    "Mandatory ID for all cash transactions",
                ],
            ),
            # ── Transaction ───────────────────────────────────────────────────
            LibraryFactor(
                ref="TXN-001",
                category_type="transaction",
                name="Structuring / smurfing",
                description="Multiple sub-threshold transactions designed to avoid TTR/IFTI reporting obligations.",
                suggested_likelihood=3,
                suggested_consequence=5,
                rationale="Structuring is a criminal offence and primary ML technique in remittance.",
                mitigation_examples=[
                    "Cumulative threshold monitoring (rolling 30-day window)",
                    "Alert on multiple transactions just below $10,000",
                ],
            ),
            LibraryFactor(
                ref="TXN-002",
                category_type="transaction",
                name="Rapid fund transfer / layering",
                description="Funds received and immediately re-transmitted onward with no apparent business purpose.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Rapid pass-through is indicative of layering — a key ML stage.",
                mitigation_examples=[
                    "Same-day outgoing hold for new customers",
                    "Alert on inbound/outbound within 24h matching amounts",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="TXN-003",
                category_type="transaction",
                name="International Fund Transfer Instructions (IFTI)",
                description="Failure to report incoming/outgoing IFTIs to AUSTRAC within 10 business days.",
                suggested_likelihood=2,
                suggested_consequence=5,
                rationale="Mandatory IFTI reporting is a core Tranche 1 obligation; non-compliance carries severe penalties.",
                mitigation_examples=[
                    "Automated IFTI generation and submission",
                    "Daily reconciliation of IFTI submissions",
                    "MLRO sign-off on delayed IFTIs",
                ],
                is_tranche1_only=True,
            ),
            # ── Regulatory ────────────────────────────────────────────────────
            LibraryFactor(
                ref="REG-001",
                category_type="regulatory",
                name="AUSTRAC registration non-compliance",
                description="Risk of operating without valid AUSTRAC registration as a remittance network provider.",
                suggested_likelihood=1,
                suggested_consequence=5,
                rationale="Operating without registration is a strict liability offence with civil penalties.",
                mitigation_examples=[
                    "Maintain registration status dashboard",
                    "Annual review of designated services declaration",
                ],
            ),
            LibraryFactor(
                ref="REG-002",
                category_type="regulatory",
                name="AML/CTF program not reviewed annually",
                description="Risk that the AML/CTF program becomes outdated and does not reflect current operations.",
                suggested_likelihood=2,
                suggested_consequence=3,
                rationale="AUSTRAC requires the program to be reviewed regularly and updated when risks change.",
                mitigation_examples=[
                    "Annual program review calendar event",
                    "Trigger review on any material business change",
                ],
            ),
        ],
    )
