from app.templates.risk.base import LibraryFactor, RiskLibrary


def get_library() -> RiskLibrary:
    return RiskLibrary(
        industry="vasp",
        description="Virtual Asset Service Provider (VASP) / Cryptocurrency exchange — Tranche 1.",
        category_weights={
            "customer": 0.20,
            "product": 0.20,
            "service": 0.10,
            "geographic": 0.15,
            "channel": 0.10,
            "transaction": 0.20,
            "regulatory": 0.05,
        },
        factors=[
            LibraryFactor(
                ref="CUST-001",
                category_type="customer",
                name="Anonymous wallet holders",
                description="Customers using self-hosted/non-custodial wallets with limited traceability.",
                suggested_likelihood=4,
                suggested_consequence=5,
                rationale="Pseudo-anonymity of blockchain addresses is the primary ML vector for VASPs.",
                mitigation_examples=[
                    "Mandatory KYC before wallet activation",
                    "Travel Rule: collect beneficiary info for transactions ≥$1,000",
                    "Blockchain analytics screening on all wallets",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="CUST-002",
                category_type="customer",
                name="High-risk jurisdiction customers",
                description="Customers or counterparties located in FATF grey/black-listed jurisdictions.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Jurisdictional risk amplifies VASP exposure to sanctions and ML.",
                mitigation_examples=[
                    "Geo-IP blocking for sanctioned jurisdictions",
                    "Enhanced CDD for high-risk jurisdiction customers",
                ],
            ),
            LibraryFactor(
                ref="CUST-003",
                category_type="customer",
                name="Politically Exposed Persons (PEPs)",
                description="PEPs or associates onboarding to exchange services.",
                suggested_likelihood=2,
                suggested_consequence=5,
                rationale="PEPs using crypto may attempt to conceal politically exposed wealth.",
                mitigation_examples=[
                    "PEP screening at onboarding and annually",
                    "MLRO approval required for PEP accounts",
                ],
            ),
            LibraryFactor(
                ref="PROD-001",
                category_type="product",
                name="Privacy coins / mixers",
                description="Trading or exchanging privacy-enhancing cryptocurrencies (Monero, Zcash) or mixer services.",
                suggested_likelihood=4,
                suggested_consequence=5,
                rationale="Privacy coins are specifically designed to defeat blockchain traceability.",
                mitigation_examples=[
                    "Prohibit privacy coin trading",
                    "Block transactions to/from known mixer addresses",
                ],
            ),
            LibraryFactor(
                ref="PROD-002",
                category_type="product",
                name="DeFi / smart contract interactions",
                description="Customers interacting with decentralised finance protocols via the platform.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="DeFi protocols often have no AML controls and facilitate rapid layering.",
                mitigation_examples=[
                    "Screen DeFi protocol addresses against sanctions",
                    "Alert on transactions to high-risk DeFi protocols",
                ],
            ),
            LibraryFactor(
                ref="GEO-001",
                category_type="geographic",
                name="Sanctioned jurisdiction transactions",
                description="Crypto transactions originating from or destined to OFAC/UN sanctioned addresses or jurisdictions.",
                suggested_likelihood=3,
                suggested_consequence=5,
                rationale="Sanctions evasion via crypto is an active regulatory enforcement area globally.",
                mitigation_examples=[
                    "Real-time OFAC/UN screening on all wallet addresses",
                    "Block sanctioned addresses at network level",
                    "Immediate MLRO escalation on sanction hit",
                ],
            ),
            LibraryFactor(
                ref="CHAN-001",
                category_type="channel",
                name="Peer-to-peer (P2P) trading",
                description="Platform facilitates direct user-to-user crypto trades without exchange intermediation.",
                suggested_likelihood=4,
                suggested_consequence=4,
                rationale="P2P trading bypasses centrally controlled transaction monitoring.",
                mitigation_examples=[
                    "Mandatory KYC on both sides of P2P trade",
                    "Escrow controls with AML checks before release",
                ],
            ),
            LibraryFactor(
                ref="TXN-001",
                category_type="transaction",
                name="High-frequency micro-transactions",
                description="Large volume of small transactions that may constitute structuring.",
                suggested_likelihood=3,
                suggested_consequence=4,
                rationale="Micro-transaction patterns can aggregate significant value while evading thresholds.",
                mitigation_examples=[
                    "Cumulative 24h/7d volume alerts",
                    "Velocity rules on number of transactions per hour",
                ],
            ),
            LibraryFactor(
                ref="TXN-002",
                category_type="transaction",
                name="Travel Rule compliance failures",
                description="Risk of non-compliance with Travel Rule obligations for VASP-to-VASP transfers.",
                suggested_likelihood=2,
                suggested_consequence=4,
                rationale="AUSTRAC requires originator/beneficiary info for transfers ≥$1,000 between VASPs.",
                mitigation_examples=[
                    "Automated Travel Rule messaging (TRISA/OpenVASP)",
                    "Reject transfers from non-compliant VASPs",
                ],
                is_tranche1_only=True,
            ),
            LibraryFactor(
                ref="TXN-003",
                category_type="transaction",
                name="Blockchain analytics — high-risk wallet exposure",
                description="Customer wallets with prior exposure to darknet markets, stolen funds, or scams.",
                suggested_likelihood=3,
                suggested_consequence=5,
                rationale="Tainted wallet exposure signals prior criminal activity; onboarding tainted wallets creates liability.",
                mitigation_examples=[
                    "Chainalysis/Elliptic screening on all deposit addresses",
                    "Block wallets with >10% tainted exposure",
                    "MLRO review for borderline exposures",
                ],
            ),
            LibraryFactor(
                ref="REG-001",
                category_type="regulatory",
                name="AUSTRAC digital currency exchange registration",
                description="Risk of operating without DCE registration under the AML/CTF Act.",
                suggested_likelihood=1,
                suggested_consequence=5,
                rationale="Unregistered DCE operation is a strict liability offence.",
                mitigation_examples=[
                    "Registration status monitoring",
                    "Legal review on any new service offerings",
                ],
            ),
        ],
    )
