"""
Regulatory Recommendation API.

Surfaces compliance decision support guidance generated by the monitoring engine
after each transaction is processed.

Roles:
  GET endpoints    — analyst+
  action/dismiss   — compliance+

DISCLAIMER: All recommendations are compliance workflow guidance only.
The reporting entity bears sole responsibility for all regulatory decisions.
"""
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.api.deps import (
    Pagination,
    org_id_for,
    require_analyst_or_above,
    require_compliance_or_above,
)
from app.db.database import get_db
from app.models.regulatory_recommendation import (
    RecommendationPriority,
    RecommendationStatus,
    RecommendationType,
    RegulatoryRecommendation,
)
from app.models.user import User
from app.services.recommendation_engine import (
    action_recommendation,
    dismiss_recommendation,
)

router = APIRouter(prefix="/recommendations", tags=["Regulatory Recommendations"])

DISCLAIMER = (
    "Recommendations are compliance workflow guidance only. "
    "The reporting entity bears sole responsibility for all regulatory decisions, "
    "including whether to lodge reports with AUSTRAC."
)


class ActionRequest(BaseModel):
    action_taken: str


class DismissRequest(BaseModel):
    dismissed_reason: str


def _rec_dict(r: RegulatoryRecommendation) -> dict:
    return {
        "id": r.id,
        "recommendation_type": r.recommendation_type.value if r.recommendation_type else None,
        "priority": r.priority.value if r.priority else None,
        "status": r.status.value if r.status else None,
        "source": r.source.value if r.source else None,
        "title": r.title,
        "recommendation_text": r.recommendation_text,
        "rationale": r.rationale,
        "regulatory_basis": r.regulatory_basis,
        "transaction_id": r.transaction_id,
        "alert_id": r.alert_id,
        "case_id": r.case_id,
        "customer_id": r.customer_id,
        "actioned_by": r.actioned_by,
        "actioned_at": r.actioned_at,
        "action_taken": r.action_taken,
        "dismissed_by": r.dismissed_by,
        "dismissed_at": r.dismissed_at,
        "dismissed_reason": r.dismissed_reason,
        "created_at": r.created_at,
        "disclaimer": DISCLAIMER,
    }


def _get_rec_or_404(rec_id: str, org_id: str, db: Session) -> RegulatoryRecommendation:
    r = db.query(RegulatoryRecommendation).filter(
        RegulatoryRecommendation.id == rec_id,
        RegulatoryRecommendation.org_id == org_id,
    ).first()
    if not r:
        raise HTTPException(404, "Recommendation not found.")
    return r


@router.get("")
def list_recommendations(
    transaction_id: Optional[str] = Query(None),
    alert_id: Optional[str] = Query(None),
    case_id: Optional[str] = Query(None),
    customer_id: Optional[str] = Query(None),
    status: Optional[RecommendationStatus] = Query(None),
    recommendation_type: Optional[RecommendationType] = Query(None),
    priority: Optional[RecommendationPriority] = Query(None),
    pagination: Pagination = Depends(),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_analyst_or_above),
):
    org_id = org_id_for(current_user)
    q = db.query(RegulatoryRecommendation).filter(
        RegulatoryRecommendation.org_id == org_id
    )
    if transaction_id:
        q = q.filter(RegulatoryRecommendation.transaction_id == transaction_id)
    if alert_id:
        q = q.filter(RegulatoryRecommendation.alert_id == alert_id)
    if case_id:
        q = q.filter(RegulatoryRecommendation.case_id == case_id)
    if customer_id:
        q = q.filter(RegulatoryRecommendation.customer_id == customer_id)
    if status:
        q = q.filter(RegulatoryRecommendation.status == status)
    if recommendation_type:
        q = q.filter(RegulatoryRecommendation.recommendation_type == recommendation_type)
    if priority:
        q = q.filter(RegulatoryRecommendation.priority == priority)

    q = q.order_by(RegulatoryRecommendation.created_at.desc())
    return [_rec_dict(r) for r in pagination.apply(q).all()]


@router.get("/dashboard")
def recommendation_dashboard(
    db: Session = Depends(get_db),
    current_user: User = Depends(require_analyst_or_above),
):
    """Pending recommendation counts by type and priority for the compliance dashboard."""
    from sqlalchemy import func
    org_id = org_id_for(current_user)

    pending_q = db.query(RegulatoryRecommendation).filter(
        RegulatoryRecommendation.org_id == org_id,
        RegulatoryRecommendation.status == RecommendationStatus.pending,
    )

    total_pending = pending_q.count()

    by_type = (
        db.query(RegulatoryRecommendation.recommendation_type, func.count(RegulatoryRecommendation.id))
        .filter(
            RegulatoryRecommendation.org_id == org_id,
            RegulatoryRecommendation.status == RecommendationStatus.pending,
        )
        .group_by(RegulatoryRecommendation.recommendation_type)
        .all()
    )

    by_priority = (
        db.query(RegulatoryRecommendation.priority, func.count(RegulatoryRecommendation.id))
        .filter(
            RegulatoryRecommendation.org_id == org_id,
            RegulatoryRecommendation.status == RecommendationStatus.pending,
        )
        .group_by(RegulatoryRecommendation.priority)
        .all()
    )

    urgent = pending_q.filter(
        RegulatoryRecommendation.priority == RecommendationPriority.urgent
    ).count()

    return {
        "pending_total": total_pending,
        "urgent": urgent,
        "by_type": {str(t): c for t, c in by_type},
        "by_priority": {str(p): c for p, c in by_priority},
        "disclaimer": DISCLAIMER,
    }


@router.get("/{rec_id}")
def get_recommendation(
    rec_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_analyst_or_above),
):
    return _rec_dict(_get_rec_or_404(rec_id, org_id_for(current_user), db))


@router.post("/{rec_id}/action")
def action_rec(
    rec_id: str,
    payload: ActionRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_compliance_or_above),
):
    """
    Mark a recommendation as actioned and document what was done.
    Required field: action_taken — a description of the action the compliance officer took.
    """
    try:
        rec = action_recommendation(rec_id, payload.action_taken, current_user.id, db, org_id_for(current_user))
    except ValueError as e:
        raise HTTPException(409, str(e))
    return _rec_dict(rec)


@router.post("/{rec_id}/dismiss")
def dismiss_rec(
    rec_id: str,
    payload: DismissRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_compliance_or_above),
):
    """
    Dismiss a recommendation with a documented reason.
    Required field: dismissed_reason — the basis for not acting on this recommendation.
    Dismissal is auditable and cannot be undone.
    """
    try:
        rec = dismiss_recommendation(rec_id, payload.dismissed_reason, current_user.id, db, org_id_for(current_user))
    except ValueError as e:
        raise HTTPException(409, str(e))
    return _rec_dict(rec)
