"""clean_domain_model_v2

Revision ID: 06699922bb99
Revises: ffafae2ef332
Create Date: 2026-06-15 03:33:06.811241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06699922bb99'
down_revision: Union[str, None] = 'ffafae2ef332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This migration replaces the legacy industry_id-based domain model (created
    # by ffafae2ef332) with the org_id-based model below, reusing several table
    # names (documents, magic_link_tokens, audit_logs, customers, users,
    # monitoring_cases, transactions, transaction_alerts). The legacy tables —
    # and the legacy-only tables that FK against them and are never recreated
    # here (ecdd_records, kyc_records, kyc_documents, compliance_reports) — are unused by current
    # app code (app/models/*) and must be dropped first so the CREATE TABLE
    # statements below don't collide with the originals.
    op.drop_table('transaction_alerts')
    op.drop_table('monitoring_cases')
    op.drop_table('kyc_documents')
    op.drop_table('kyc_records')
    op.drop_table('ecdd_records')
    op.drop_table('transactions')
    op.drop_table('compliance_reports')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('audit_logs')
    op.drop_table('documents')
    op.drop_table('magic_link_tokens')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=60), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.Enum('kyc', 'aml', 'report', 'case', 'ecdd', 'contract', 'policy', 'correspondence', 'other', name='documentcategory'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='documentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('abn', sa.String(length=11), nullable=True),
    sa.Column('acn', sa.String(length=9), nullable=True),
    sa.Column('austrac_id', sa.String(length=50), nullable=True),
    sa.Column('industry_type', sa.Enum('banking', 'fintech', 'insurance', 'real_estate', 'cryptocurrency', 'remittance', 'designated_remittance', 'other', name='industrytype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'inactive', 'pending', name='organisationstatus'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abn')
    )
    op.create_table('aml_programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'under_review', 'superseded', name='programstatus'), nullable=False),
    sa.Column('risk_appetite', sa.Enum('low', 'medium', 'high', name='riskappetite'), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('policies_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_programs_org_id'), 'aml_programs', ['org_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('customer_type', sa.Enum('individual', 'business', 'trust', 'partnership', name='customertype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'under_review', 'active', 'suspended', 'rejected', 'closed', name='customerstatus'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('country_of_residence', sa.String(length=2), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('abn', sa.String(length=11), nullable=True),
    sa.Column('acn', sa.String(length=9), nullable=True),
    sa.Column('business_structure', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id_type', sa.Enum('passport', 'drivers_licence', 'national_id', 'medicare', 'other', name='idtype'), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('id_expiry', sa.Date(), nullable=True),
    sa.Column('id_issuing_country', sa.String(length=2), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('source_of_funds', sa.String(length=500), nullable=True),
    sa.Column('source_of_wealth', sa.String(length=500), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=True),
    sa.Column('pep_details', sa.Text(), nullable=True),
    sa.Column('onboarded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_org_id'), 'customers', ['org_id'], unique=False)
    op.create_table('pep_screenings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('customer', 'beneficial_owner', name='screeningentitytype'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('screened_by', sa.String(), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'clear', 'potential_match', 'confirmed_match', 'false_positive', name='screeningstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_details', sa.JSON(), nullable=True),
    sa.Column('pep_category', sa.String(length=100), nullable=True),
    sa.Column('pep_country', sa.String(length=2), nullable=True),
    sa.Column('pep_position', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pep_screenings_entity_id'), 'pep_screenings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_pep_screenings_org_id'), 'pep_screenings', ['org_id'], unique=False)
    op.create_table('sanctions_screenings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('customer', 'beneficial_owner', name='screeningentitytype'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('screened_by', sa.String(), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'clear', 'potential_match', 'confirmed_match', 'false_positive', name='screeningstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_details', sa.JSON(), nullable=True),
    sa.Column('lists_checked', sa.JSON(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_screenings_entity_id'), 'sanctions_screenings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sanctions_screenings_org_id'), 'sanctions_screenings', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'mlro', 'compliance', 'analyst', 'viewer', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'pending_mfa', name='userstatus'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('beneficial_owners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('country_of_residence', sa.String(length=2), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id_type', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('id_expiry', sa.Date(), nullable=True),
    sa.Column('ownership_percentage', sa.Float(), nullable=True),
    sa.Column('ownership_type', sa.Enum('direct', 'indirect', 'beneficial', name='ownershiptype'), nullable=True),
    sa.Column('is_controlling_person', sa.Boolean(), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=True),
    sa.Column('pep_details', sa.Text(), nullable=True),
    sa.Column('source_of_wealth', sa.String(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficial_owners_customer_id'), 'beneficial_owners', ['customer_id'], unique=False)
    op.create_index(op.f('ix_beneficial_owners_org_id'), 'beneficial_owners', ['org_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='caseseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_investigation', 'pending_review', 'escalated', 'closed_no_action', 'closed_reported', 'closed_referred', name='casestatus'), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_to', sa.String(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('related_transaction_ids', sa.JSON(), nullable=True),
    sa.Column('related_report_ids', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_org_id'), 'cases', ['org_id'], unique=False)
    op.create_table('monitoring_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('alert_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_cases_case_id'), 'monitoring_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_monitoring_cases_id'), 'monitoring_cases', ['id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('aml_program_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'approved', name='assessmentstatus'), nullable=False),
    sa.Column('inherent_risk_score', sa.Float(), nullable=True),
    sa.Column('control_effectiveness_score', sa.Float(), nullable=True),
    sa.Column('residual_risk_score', sa.Float(), nullable=True),
    sa.Column('customer_risk_rating', sa.String(length=20), nullable=True),
    sa.Column('product_risk_rating', sa.String(length=20), nullable=True),
    sa.Column('channel_risk_rating', sa.String(length=20), nullable=True),
    sa.Column('geography_risk_rating', sa.String(length=20), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conducted_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aml_program_id'], ['aml_programs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_aml_program_id'), 'risk_assessments', ['aml_program_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_org_id'), 'risk_assessments', ['org_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('deposit', 'withdrawal', 'transfer', 'payment', 'exchange', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount_aud', sa.Float(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_account', sa.String(length=100), nullable=True),
    sa.Column('counterparty_country', sa.String(length=10), nullable=True),
    sa.Column('counterparty_bank', sa.String(length=200), nullable=True),
    sa.Column('is_cross_border', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'flagged', 'blocked', 'under_review', 'cleared', name='transactionstatus'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_suspicious', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('large_transaction', 'structuring', 'rapid_movement', 'high_risk_country', 'unusual_pattern', 'sanctions_match', 'velocity_breach', 'cross_border', 'pep_transaction', 'rule_triggered', name='alerttype'), nullable=True),
    sa.Column('alert_details', sa.Text(), nullable=True),
    sa.Column('rule_matches', sa.JSON(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('case_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('ifti_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='iftidirection'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'submitted', 'acknowledged', 'rejected', name='reportstatus'), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('date_available', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=True),
    sa.Column('transfer_reference', sa.String(length=100), nullable=True),
    sa.Column('oc_name', sa.String(length=255), nullable=True),
    sa.Column('oc_dob', sa.Date(), nullable=True),
    sa.Column('oc_address', sa.String(length=500), nullable=True),
    sa.Column('oc_postal_address', sa.String(length=500), nullable=True),
    sa.Column('oc_contact', sa.String(length=255), nullable=True),
    sa.Column('oc_occupation', sa.String(length=255), nullable=True),
    sa.Column('oc_abn', sa.String(length=11), nullable=True),
    sa.Column('oc_account_number', sa.String(length=50), nullable=True),
    sa.Column('oc_business_structure', sa.String(length=50), nullable=True),
    sa.Column('oc_id1_type', sa.String(length=50), nullable=True),
    sa.Column('oc_id1_number', sa.String(length=50), nullable=True),
    sa.Column('oc_id1_country', sa.String(length=2), nullable=True),
    sa.Column('oc_id2_type', sa.String(length=50), nullable=True),
    sa.Column('oc_id2_number', sa.String(length=50), nullable=True),
    sa.Column('oc_id2_country', sa.String(length=2), nullable=True),
    sa.Column('oc_electronic_source', sa.String(length=255), nullable=True),
    sa.Column('bc_name', sa.String(length=255), nullable=True),
    sa.Column('bc_dob', sa.Date(), nullable=True),
    sa.Column('bc_business_name', sa.String(length=255), nullable=True),
    sa.Column('bc_address', sa.String(length=500), nullable=True),
    sa.Column('bc_postal_address', sa.String(length=500), nullable=True),
    sa.Column('bc_account_number', sa.String(length=50), nullable=True),
    sa.Column('bc_institution_name', sa.String(length=255), nullable=True),
    sa.Column('bc_institution_country', sa.String(length=2), nullable=True),
    sa.Column('bc_swift_bic', sa.String(length=11), nullable=True),
    sa.Column('reason_for_transfer', sa.String(length=500), nullable=True),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_abn', sa.String(length=11), nullable=True),
    sa.Column('reporter_austrac_id', sa.String(length=50), nullable=True),
    sa.Column('reporter_contact', sa.String(length=255), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifti_reports_customer_id'), 'ifti_reports', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ifti_reports_org_id'), 'ifti_reports', ['org_id'], unique=False)
    op.create_table('smr_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'submitted', 'acknowledged', 'rejected', name='reportstatus'), nullable=False),
    sa.Column('matter_date', sa.Date(), nullable=False),
    sa.Column('suspicion_grounds', sa.Text(), nullable=False),
    sa.Column('transaction_ids', sa.JSON(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('subject_dob', sa.Date(), nullable=True),
    sa.Column('subject_address', sa.String(length=500), nullable=True),
    sa.Column('subject_occupation', sa.String(length=255), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('mlro_sign_off', sa.String(), nullable=True),
    sa.Column('mlro_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smr_reports_case_id'), 'smr_reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_smr_reports_customer_id'), 'smr_reports', ['customer_id'], unique=False)
    op.create_index(op.f('ix_smr_reports_org_id'), 'smr_reports', ['org_id'], unique=False)
    op.create_table('transaction_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('alert_type', sa.Enum('large_transaction', 'structuring', 'rapid_movement', 'high_risk_country', 'unusual_pattern', 'sanctions_match', 'velocity_breach', 'cross_border', 'pep_transaction', 'rule_triggered', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'escalated', 'dismissed', 'resolved', 'reported', name='alertstatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('rule_name', sa.String(length=200), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('escalated_to', sa.String(length=200), nullable=True),
    sa.Column('is_resolved', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_alerts_alert_id'), 'transaction_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_transaction_alerts_id'), 'transaction_alerts', ['id'], unique=False)
    op.create_table('ttr_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'submitted', 'acknowledged', 'rejected', name='reportstatus'), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_dob', sa.Date(), nullable=True),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('customer_occupation', sa.String(length=255), nullable=True),
    sa.Column('customer_id_type', sa.String(length=50), nullable=True),
    sa.Column('customer_id_number', sa.String(length=50), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('branch_address', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ttr_reports_customer_id'), 'ttr_reports', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ttr_reports_org_id'), 'ttr_reports', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ttr_reports_org_id'), table_name='ttr_reports')
    op.drop_index(op.f('ix_ttr_reports_customer_id'), table_name='ttr_reports')
    op.drop_table('ttr_reports')
    op.drop_index(op.f('ix_transaction_alerts_id'), table_name='transaction_alerts')
    op.drop_index(op.f('ix_transaction_alerts_alert_id'), table_name='transaction_alerts')
    op.drop_table('transaction_alerts')
    op.drop_index(op.f('ix_smr_reports_org_id'), table_name='smr_reports')
    op.drop_index(op.f('ix_smr_reports_customer_id'), table_name='smr_reports')
    op.drop_index(op.f('ix_smr_reports_case_id'), table_name='smr_reports')
    op.drop_table('smr_reports')
    op.drop_index(op.f('ix_ifti_reports_org_id'), table_name='ifti_reports')
    op.drop_index(op.f('ix_ifti_reports_customer_id'), table_name='ifti_reports')
    op.drop_table('ifti_reports')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_risk_assessments_org_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_aml_program_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_monitoring_cases_id'), table_name='monitoring_cases')
    op.drop_index(op.f('ix_monitoring_cases_case_id'), table_name='monitoring_cases')
    op.drop_table('monitoring_cases')
    op.drop_index(op.f('ix_cases_org_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_customer_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_beneficial_owners_org_id'), table_name='beneficial_owners')
    op.drop_index(op.f('ix_beneficial_owners_customer_id'), table_name='beneficial_owners')
    op.drop_table('beneficial_owners')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sanctions_screenings_org_id'), table_name='sanctions_screenings')
    op.drop_index(op.f('ix_sanctions_screenings_entity_id'), table_name='sanctions_screenings')
    op.drop_table('sanctions_screenings')
    op.drop_index(op.f('ix_pep_screenings_org_id'), table_name='pep_screenings')
    op.drop_index(op.f('ix_pep_screenings_entity_id'), table_name='pep_screenings')
    op.drop_table('pep_screenings')
    op.drop_index(op.f('ix_customers_org_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_aml_programs_org_id'), table_name='aml_programs')
    op.drop_table('aml_programs')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
