"""org_scoped_fk_ondelete

Critical #11 (scoped): most FKs in this codebase referencing
organisations.id / users.id had no ondelete= clause, defaulting to
Postgres's NO ACTION/RESTRICT — deleting an org or a user blocked on any
referencing row instead of cleanly cascading or nulling out actor
references. This migration applies the org-scoped subset of the fix:

  - organisations.id FKs -> ON DELETE CASCADE (deleting an org cleanly
    removes its data, matching the existing pattern already used by
    customers/transactions/screening/monitoring tables).
  - users.id "actor/owner" FKs (created_by, reviewer_id, uploaded_by,
    etc.) that are nullable -> ON DELETE SET NULL (deleting a user
    shouldn't delete records they touched).

customers.id-referencing FKs and non-nullable users.id FKs are
deliberately out of scope for this migration (follow-up item).

Assumes Postgres's default auto-generated constraint name
(<table>_<column>_fkey) since no naming_convention is configured on
Base.metadata — see alembic/versions/f73383da4e36_baseline_sync_with_models.py.

Revision ID: c7d8e9f0a1b2
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7d8e9f0a1b2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('ALTER TABLE aml_programs DROP CONSTRAINT IF EXISTS aml_programs_compliance_officer_user_id_fkey')
    op.create_foreign_key("aml_programs_compliance_officer_user_id_fkey", "aml_programs", "users", ["compliance_officer_user_id"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE aml_programs DROP CONSTRAINT IF EXISTS aml_programs_org_id_fkey')
    op.create_foreign_key("aml_programs_org_id_fkey", "aml_programs", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE aml_services DROP CONSTRAINT IF EXISTS aml_services_org_id_fkey')
    op.create_foreign_key("aml_services_org_id_fkey", "aml_services", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE aml_solutions DROP CONSTRAINT IF EXISTS aml_solutions_org_id_fkey')
    op.create_foreign_key("aml_solutions_org_id_fkey", "aml_solutions", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE assessment_outcome_flags DROP CONSTRAINT IF EXISTS assessment_outcome_flags_org_id_fkey')
    op.create_foreign_key("assessment_outcome_flags_org_id_fkey", "assessment_outcome_flags", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE assessment_outcome_flags DROP CONSTRAINT IF EXISTS assessment_outcome_flags_reviewed_by_fkey')
    op.create_foreign_key("assessment_outcome_flags_reviewed_by_fkey", "assessment_outcome_flags", "users", ["reviewed_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_org_id_fkey')
    op.create_foreign_key("audit_logs_org_id_fkey", "audit_logs", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE automation_rules DROP CONSTRAINT IF EXISTS automation_rules_org_id_fkey')
    op.create_foreign_key("automation_rules_org_id_fkey", "automation_rules", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE board_reports DROP CONSTRAINT IF EXISTS board_reports_org_id_fkey')
    op.create_foreign_key("board_reports_org_id_fkey", "board_reports", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE cases DROP CONSTRAINT IF EXISTS cases_org_id_fkey')
    op.create_foreign_key("cases_org_id_fkey", "cases", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE compliance_calendar DROP CONSTRAINT IF EXISTS compliance_calendar_org_id_fkey')
    op.create_foreign_key("compliance_calendar_org_id_fkey", "compliance_calendar", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE compliance_reminders DROP CONSTRAINT IF EXISTS compliance_reminders_org_id_fkey')
    op.create_foreign_key("compliance_reminders_org_id_fkey", "compliance_reminders", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE control_evidence_items DROP CONSTRAINT IF EXISTS control_evidence_items_org_id_fkey')
    op.create_foreign_key("control_evidence_items_org_id_fkey", "control_evidence_items", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE control_evidence_items DROP CONSTRAINT IF EXISTS control_evidence_items_uploaded_by_fkey')
    op.create_foreign_key("control_evidence_items_uploaded_by_fkey", "control_evidence_items", "users", ["uploaded_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_closed_by_fkey')
    op.create_foreign_key("control_remediation_actions_closed_by_fkey", "control_remediation_actions", "users", ["closed_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_escalation_owner_id_fkey')
    op.create_foreign_key("control_remediation_actions_escalation_owner_id_fkey", "control_remediation_actions", "users", ["escalation_owner_id"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_org_id_fkey')
    op.create_foreign_key("control_remediation_actions_org_id_fkey", "control_remediation_actions", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_risk_acceptance_by_fkey')
    op.create_foreign_key("control_remediation_actions_risk_acceptance_by_fkey", "control_remediation_actions", "users", ["risk_acceptance_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE control_test_findings DROP CONSTRAINT IF EXISTS control_test_findings_org_id_fkey')
    op.create_foreign_key("control_test_findings_org_id_fkey", "control_test_findings", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE control_tests DROP CONSTRAINT IF EXISTS control_tests_org_id_fkey')
    op.create_foreign_key("control_tests_org_id_fkey", "control_tests", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE control_tests DROP CONSTRAINT IF EXISTS control_tests_reviewed_by_fkey')
    op.create_foreign_key("control_tests_reviewed_by_fkey", "control_tests", "users", ["reviewed_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE controls DROP CONSTRAINT IF EXISTS controls_org_id_fkey')
    op.create_foreign_key("controls_org_id_fkey", "controls", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE customer_portal_sessions DROP CONSTRAINT IF EXISTS customer_portal_sessions_org_id_fkey')
    op.create_foreign_key("customer_portal_sessions_org_id_fkey", "customer_portal_sessions", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_organisation_id_fkey')
    op.create_foreign_key("documents_organisation_id_fkey", "documents", "organisations", ["organisation_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE filing_register DROP CONSTRAINT IF EXISTS filing_register_org_id_fkey')
    op.create_foreign_key("filing_register_org_id_fkey", "filing_register", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_approval_matrix DROP CONSTRAINT IF EXISTS governance_approval_matrix_created_by_fkey')
    op.create_foreign_key("governance_approval_matrix_created_by_fkey", "governance_approval_matrix", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_approval_matrix DROP CONSTRAINT IF EXISTS governance_approval_matrix_org_id_fkey')
    op.create_foreign_key("governance_approval_matrix_org_id_fkey", "governance_approval_matrix", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_controls DROP CONSTRAINT IF EXISTS governance_controls_auditor_id_fkey')
    op.create_foreign_key("governance_controls_auditor_id_fkey", "governance_controls", "users", ["auditor_id"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_controls DROP CONSTRAINT IF EXISTS governance_controls_org_id_fkey')
    op.create_foreign_key("governance_controls_org_id_fkey", "governance_controls", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_controls DROP CONSTRAINT IF EXISTS governance_controls_reviewer_id_fkey')
    op.create_foreign_key("governance_controls_reviewer_id_fkey", "governance_controls", "users", ["reviewer_id"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_custom_fields DROP CONSTRAINT IF EXISTS governance_custom_fields_created_by_fkey')
    op.create_foreign_key("governance_custom_fields_created_by_fkey", "governance_custom_fields", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_custom_fields DROP CONSTRAINT IF EXISTS governance_custom_fields_org_id_fkey')
    op.create_foreign_key("governance_custom_fields_org_id_fkey", "governance_custom_fields", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_custom_lists DROP CONSTRAINT IF EXISTS governance_custom_lists_created_by_fkey')
    op.create_foreign_key("governance_custom_lists_created_by_fkey", "governance_custom_lists", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_custom_lists DROP CONSTRAINT IF EXISTS governance_custom_lists_org_id_fkey')
    op.create_foreign_key("governance_custom_lists_org_id_fkey", "governance_custom_lists", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_custom_scoring DROP CONSTRAINT IF EXISTS governance_custom_scoring_org_id_fkey')
    op.create_foreign_key("governance_custom_scoring_org_id_fkey", "governance_custom_scoring", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_custom_scoring DROP CONSTRAINT IF EXISTS governance_custom_scoring_updated_by_fkey')
    op.create_foreign_key("governance_custom_scoring_updated_by_fkey", "governance_custom_scoring", "users", ["updated_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_custom_workflows DROP CONSTRAINT IF EXISTS governance_custom_workflows_created_by_fkey')
    op.create_foreign_key("governance_custom_workflows_created_by_fkey", "governance_custom_workflows", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_custom_workflows DROP CONSTRAINT IF EXISTS governance_custom_workflows_org_id_fkey')
    op.create_foreign_key("governance_custom_workflows_org_id_fkey", "governance_custom_workflows", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_custom_workflows DROP CONSTRAINT IF EXISTS governance_custom_workflows_specific_user_id_fkey')
    op.create_foreign_key("governance_custom_workflows_specific_user_id_fkey", "governance_custom_workflows", "users", ["specific_user_id"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_dashboard_metrics DROP CONSTRAINT IF EXISTS governance_dashboard_metrics_created_by_fkey')
    op.create_foreign_key("governance_dashboard_metrics_created_by_fkey", "governance_dashboard_metrics", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_dashboard_metrics DROP CONSTRAINT IF EXISTS governance_dashboard_metrics_org_id_fkey')
    op.create_foreign_key("governance_dashboard_metrics_org_id_fkey", "governance_dashboard_metrics", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_approver_fkey')
    op.create_foreign_key("governance_policies_approver_fkey", "governance_policies", "users", ["approver"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_compliance_reviewer_fkey')
    op.create_foreign_key("governance_policies_compliance_reviewer_fkey", "governance_policies", "users", ["compliance_reviewer"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_internal_reviewer_fkey')
    op.create_foreign_key("governance_policies_internal_reviewer_fkey", "governance_policies", "users", ["internal_reviewer"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_org_id_fkey')
    op.create_foreign_key("governance_policies_org_id_fkey", "governance_policies", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE governance_training_records DROP CONSTRAINT IF EXISTS governance_training_records_assigned_by_fkey')
    op.create_foreign_key("governance_training_records_assigned_by_fkey", "governance_training_records", "users", ["assigned_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_training_records DROP CONSTRAINT IF EXISTS governance_training_records_exemption_approved_by_fkey')
    op.create_foreign_key("governance_training_records_exemption_approved_by_fkey", "governance_training_records", "users", ["exemption_approved_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE governance_training_records DROP CONSTRAINT IF EXISTS governance_training_records_org_id_fkey')
    op.create_foreign_key("governance_training_records_org_id_fkey", "governance_training_records", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE ifti_receipts DROP CONSTRAINT IF EXISTS ifti_receipts_org_id_fkey')
    op.create_foreign_key("ifti_receipts_org_id_fkey", "ifti_receipts", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE ifti_reports DROP CONSTRAINT IF EXISTS ifti_reports_org_id_fkey')
    op.create_foreign_key("ifti_reports_org_id_fkey", "ifti_reports", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE independent_reviews DROP CONSTRAINT IF EXISTS independent_reviews_org_id_fkey')
    op.create_foreign_key("independent_reviews_org_id_fkey", "independent_reviews", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_approval_questions DROP CONSTRAINT IF EXISTS org_approval_questions_org_id_fkey')
    op.create_foreign_key("org_approval_questions_org_id_fkey", "org_approval_questions", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_integrations DROP CONSTRAINT IF EXISTS org_integrations_org_id_fkey')
    op.create_foreign_key("org_integrations_org_id_fkey", "org_integrations", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_metrics_snapshots DROP CONSTRAINT IF EXISTS org_metrics_snapshots_org_id_fkey')
    op.create_foreign_key("org_metrics_snapshots_org_id_fkey", "org_metrics_snapshots", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_monitoring_configs DROP CONSTRAINT IF EXISTS org_monitoring_configs_org_id_fkey')
    op.create_foreign_key("org_monitoring_configs_org_id_fkey", "org_monitoring_configs", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_professional_checklist_templates DROP CONSTRAINT IF EXISTS org_professional_checklist_templates_org_id_fkey')
    op.create_foreign_key("org_professional_checklist_templates_org_id_fkey", "org_professional_checklist_templates", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_risk_factors DROP CONSTRAINT IF EXISTS org_risk_factors_org_id_fkey')
    op.create_foreign_key("org_risk_factors_org_id_fkey", "org_risk_factors", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_risk_matrix_versions DROP CONSTRAINT IF EXISTS org_risk_matrix_versions_org_id_fkey')
    op.create_foreign_key("org_risk_matrix_versions_org_id_fkey", "org_risk_matrix_versions", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE org_risk_profiles DROP CONSTRAINT IF EXISTS org_risk_profiles_org_id_fkey')
    op.create_foreign_key("org_risk_profiles_org_id_fkey", "org_risk_profiles", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE organisation_users DROP CONSTRAINT IF EXISTS organisation_users_organisation_id_fkey')
    op.create_foreign_key("organisation_users_organisation_id_fkey", "organisation_users", "organisations", ["organisation_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE policies DROP CONSTRAINT IF EXISTS policies_org_id_fkey')
    op.create_foreign_key("policies_org_id_fkey", "policies", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE policy_attestations DROP CONSTRAINT IF EXISTS policy_attestations_org_id_fkey')
    op.create_foreign_key("policy_attestations_org_id_fkey", "policy_attestations", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE policy_review_reminders DROP CONSTRAINT IF EXISTS policy_review_reminders_org_id_fkey')
    op.create_foreign_key("policy_review_reminders_org_id_fkey", "policy_review_reminders", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE policy_versions DROP CONSTRAINT IF EXISTS policy_versions_org_id_fkey')
    op.create_foreign_key("policy_versions_org_id_fkey", "policy_versions", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE policy_workflow_events DROP CONSTRAINT IF EXISTS policy_workflow_events_org_id_fkey')
    op.create_foreign_key("policy_workflow_events_org_id_fkey", "policy_workflow_events", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE professional_assessments DROP CONSTRAINT IF EXISTS professional_assessments_org_id_fkey')
    op.create_foreign_key("professional_assessments_org_id_fkey", "professional_assessments", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE regulatory_recommendations DROP CONSTRAINT IF EXISTS regulatory_recommendations_org_id_fkey')
    op.create_foreign_key("regulatory_recommendations_org_id_fkey", "regulatory_recommendations", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE reporting_group_members DROP CONSTRAINT IF EXISTS reporting_group_members_org_id_fkey')
    op.create_foreign_key("reporting_group_members_org_id_fkey", "reporting_group_members", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE reporting_groups DROP CONSTRAINT IF EXISTS reporting_groups_holding_org_id_fkey')
    op.create_foreign_key("reporting_groups_holding_org_id_fkey", "reporting_groups", "organisations", ["holding_org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_assessment_runs DROP CONSTRAINT IF EXISTS risk_assessment_runs_org_id_fkey')
    op.create_foreign_key("risk_assessment_runs_org_id_fkey", "risk_assessment_runs", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_assessments DROP CONSTRAINT IF EXISTS risk_assessments_org_id_fkey')
    op.create_foreign_key("risk_assessments_org_id_fkey", "risk_assessments", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_categories DROP CONSTRAINT IF EXISTS risk_categories_org_id_fkey')
    op.create_foreign_key("risk_categories_org_id_fkey", "risk_categories", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_controls DROP CONSTRAINT IF EXISTS risk_controls_org_id_fkey')
    op.create_foreign_key("risk_controls_org_id_fkey", "risk_controls", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_factor_scores DROP CONSTRAINT IF EXISTS risk_factor_scores_org_id_fkey')
    op.create_foreign_key("risk_factor_scores_org_id_fkey", "risk_factor_scores", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_factors DROP CONSTRAINT IF EXISTS risk_factors_org_id_fkey')
    op.create_foreign_key("risk_factors_org_id_fkey", "risk_factors", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_frameworks DROP CONSTRAINT IF EXISTS risk_frameworks_org_id_fkey')
    op.create_foreign_key("risk_frameworks_org_id_fkey", "risk_frameworks", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE risk_mitigations DROP CONSTRAINT IF EXISTS risk_mitigations_org_id_fkey')
    op.create_foreign_key("risk_mitigations_org_id_fkey", "risk_mitigations", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_organisation_id_fkey')
    op.create_foreign_key("roles_organisation_id_fkey", "roles", "organisations", ["organisation_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE smr_reports DROP CONSTRAINT IF EXISTS smr_reports_org_id_fkey')
    op.create_foreign_key("smr_reports_org_id_fkey", "smr_reports", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_org_id_fkey')
    op.create_foreign_key("tasks_org_id_fkey", "tasks", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE training_assignments DROP CONSTRAINT IF EXISTS training_assignments_org_id_fkey')
    op.create_foreign_key("training_assignments_org_id_fkey", "training_assignments", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE training_courses DROP CONSTRAINT IF EXISTS training_courses_created_by_fkey')
    op.create_foreign_key("training_courses_created_by_fkey", "training_courses", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.execute('ALTER TABLE training_courses DROP CONSTRAINT IF EXISTS training_courses_org_id_fkey')
    op.create_foreign_key("training_courses_org_id_fkey", "training_courses", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE training_records DROP CONSTRAINT IF EXISTS training_records_org_id_fkey')
    op.create_foreign_key("training_records_org_id_fkey", "training_records", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE training_trigger_logs DROP CONSTRAINT IF EXISTS training_trigger_logs_org_id_fkey')
    op.create_foreign_key("training_trigger_logs_org_id_fkey", "training_trigger_logs", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE training_trigger_rules DROP CONSTRAINT IF EXISTS training_trigger_rules_org_id_fkey')
    op.create_foreign_key("training_trigger_rules_org_id_fkey", "training_trigger_rules", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE ttr_reports DROP CONSTRAINT IF EXISTS ttr_reports_org_id_fkey')
    op.create_foreign_key("ttr_reports_org_id_fkey", "ttr_reports", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_org_id_fkey')
    op.create_foreign_key("users_org_id_fkey", "users", "organisations", ["org_id"], ["id"], ondelete="CASCADE")
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_primary_organisation_id_fkey')
    op.create_foreign_key("users_primary_organisation_id_fkey", "users", "organisations", ["primary_organisation_id"], ["id"], ondelete="SET NULL")


def downgrade() -> None:
    op.execute('ALTER TABLE aml_programs DROP CONSTRAINT IF EXISTS aml_programs_compliance_officer_user_id_fkey')
    op.create_foreign_key("aml_programs_compliance_officer_user_id_fkey", "aml_programs", "users", ["compliance_officer_user_id"], ["id"])
    op.execute('ALTER TABLE aml_programs DROP CONSTRAINT IF EXISTS aml_programs_org_id_fkey')
    op.create_foreign_key("aml_programs_org_id_fkey", "aml_programs", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE aml_services DROP CONSTRAINT IF EXISTS aml_services_org_id_fkey')
    op.create_foreign_key("aml_services_org_id_fkey", "aml_services", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE aml_solutions DROP CONSTRAINT IF EXISTS aml_solutions_org_id_fkey')
    op.create_foreign_key("aml_solutions_org_id_fkey", "aml_solutions", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE assessment_outcome_flags DROP CONSTRAINT IF EXISTS assessment_outcome_flags_org_id_fkey')
    op.create_foreign_key("assessment_outcome_flags_org_id_fkey", "assessment_outcome_flags", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE assessment_outcome_flags DROP CONSTRAINT IF EXISTS assessment_outcome_flags_reviewed_by_fkey')
    op.create_foreign_key("assessment_outcome_flags_reviewed_by_fkey", "assessment_outcome_flags", "users", ["reviewed_by"], ["id"])
    op.execute('ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_org_id_fkey')
    op.create_foreign_key("audit_logs_org_id_fkey", "audit_logs", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE automation_rules DROP CONSTRAINT IF EXISTS automation_rules_org_id_fkey')
    op.create_foreign_key("automation_rules_org_id_fkey", "automation_rules", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE board_reports DROP CONSTRAINT IF EXISTS board_reports_org_id_fkey')
    op.create_foreign_key("board_reports_org_id_fkey", "board_reports", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE cases DROP CONSTRAINT IF EXISTS cases_org_id_fkey')
    op.create_foreign_key("cases_org_id_fkey", "cases", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE compliance_calendar DROP CONSTRAINT IF EXISTS compliance_calendar_org_id_fkey')
    op.create_foreign_key("compliance_calendar_org_id_fkey", "compliance_calendar", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE compliance_reminders DROP CONSTRAINT IF EXISTS compliance_reminders_org_id_fkey')
    op.create_foreign_key("compliance_reminders_org_id_fkey", "compliance_reminders", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE control_evidence_items DROP CONSTRAINT IF EXISTS control_evidence_items_org_id_fkey')
    op.create_foreign_key("control_evidence_items_org_id_fkey", "control_evidence_items", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE control_evidence_items DROP CONSTRAINT IF EXISTS control_evidence_items_uploaded_by_fkey')
    op.create_foreign_key("control_evidence_items_uploaded_by_fkey", "control_evidence_items", "users", ["uploaded_by"], ["id"])
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_closed_by_fkey')
    op.create_foreign_key("control_remediation_actions_closed_by_fkey", "control_remediation_actions", "users", ["closed_by"], ["id"])
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_escalation_owner_id_fkey')
    op.create_foreign_key("control_remediation_actions_escalation_owner_id_fkey", "control_remediation_actions", "users", ["escalation_owner_id"], ["id"])
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_org_id_fkey')
    op.create_foreign_key("control_remediation_actions_org_id_fkey", "control_remediation_actions", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE control_remediation_actions DROP CONSTRAINT IF EXISTS control_remediation_actions_risk_acceptance_by_fkey')
    op.create_foreign_key("control_remediation_actions_risk_acceptance_by_fkey", "control_remediation_actions", "users", ["risk_acceptance_by"], ["id"])
    op.execute('ALTER TABLE control_test_findings DROP CONSTRAINT IF EXISTS control_test_findings_org_id_fkey')
    op.create_foreign_key("control_test_findings_org_id_fkey", "control_test_findings", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE control_tests DROP CONSTRAINT IF EXISTS control_tests_org_id_fkey')
    op.create_foreign_key("control_tests_org_id_fkey", "control_tests", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE control_tests DROP CONSTRAINT IF EXISTS control_tests_reviewed_by_fkey')
    op.create_foreign_key("control_tests_reviewed_by_fkey", "control_tests", "users", ["reviewed_by"], ["id"])
    op.execute('ALTER TABLE controls DROP CONSTRAINT IF EXISTS controls_org_id_fkey')
    op.create_foreign_key("controls_org_id_fkey", "controls", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE customer_portal_sessions DROP CONSTRAINT IF EXISTS customer_portal_sessions_org_id_fkey')
    op.create_foreign_key("customer_portal_sessions_org_id_fkey", "customer_portal_sessions", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_organisation_id_fkey')
    op.create_foreign_key("documents_organisation_id_fkey", "documents", "organisations", ["organisation_id"], ["id"])
    op.execute('ALTER TABLE filing_register DROP CONSTRAINT IF EXISTS filing_register_org_id_fkey')
    op.create_foreign_key("filing_register_org_id_fkey", "filing_register", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_approval_matrix DROP CONSTRAINT IF EXISTS governance_approval_matrix_created_by_fkey')
    op.create_foreign_key("governance_approval_matrix_created_by_fkey", "governance_approval_matrix", "users", ["created_by"], ["id"])
    op.execute('ALTER TABLE governance_approval_matrix DROP CONSTRAINT IF EXISTS governance_approval_matrix_org_id_fkey')
    op.create_foreign_key("governance_approval_matrix_org_id_fkey", "governance_approval_matrix", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_controls DROP CONSTRAINT IF EXISTS governance_controls_auditor_id_fkey')
    op.create_foreign_key("governance_controls_auditor_id_fkey", "governance_controls", "users", ["auditor_id"], ["id"])
    op.execute('ALTER TABLE governance_controls DROP CONSTRAINT IF EXISTS governance_controls_org_id_fkey')
    op.create_foreign_key("governance_controls_org_id_fkey", "governance_controls", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_controls DROP CONSTRAINT IF EXISTS governance_controls_reviewer_id_fkey')
    op.create_foreign_key("governance_controls_reviewer_id_fkey", "governance_controls", "users", ["reviewer_id"], ["id"])
    op.execute('ALTER TABLE governance_custom_fields DROP CONSTRAINT IF EXISTS governance_custom_fields_created_by_fkey')
    op.create_foreign_key("governance_custom_fields_created_by_fkey", "governance_custom_fields", "users", ["created_by"], ["id"])
    op.execute('ALTER TABLE governance_custom_fields DROP CONSTRAINT IF EXISTS governance_custom_fields_org_id_fkey')
    op.create_foreign_key("governance_custom_fields_org_id_fkey", "governance_custom_fields", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_custom_lists DROP CONSTRAINT IF EXISTS governance_custom_lists_created_by_fkey')
    op.create_foreign_key("governance_custom_lists_created_by_fkey", "governance_custom_lists", "users", ["created_by"], ["id"])
    op.execute('ALTER TABLE governance_custom_lists DROP CONSTRAINT IF EXISTS governance_custom_lists_org_id_fkey')
    op.create_foreign_key("governance_custom_lists_org_id_fkey", "governance_custom_lists", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_custom_scoring DROP CONSTRAINT IF EXISTS governance_custom_scoring_org_id_fkey')
    op.create_foreign_key("governance_custom_scoring_org_id_fkey", "governance_custom_scoring", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_custom_scoring DROP CONSTRAINT IF EXISTS governance_custom_scoring_updated_by_fkey')
    op.create_foreign_key("governance_custom_scoring_updated_by_fkey", "governance_custom_scoring", "users", ["updated_by"], ["id"])
    op.execute('ALTER TABLE governance_custom_workflows DROP CONSTRAINT IF EXISTS governance_custom_workflows_created_by_fkey')
    op.create_foreign_key("governance_custom_workflows_created_by_fkey", "governance_custom_workflows", "users", ["created_by"], ["id"])
    op.execute('ALTER TABLE governance_custom_workflows DROP CONSTRAINT IF EXISTS governance_custom_workflows_org_id_fkey')
    op.create_foreign_key("governance_custom_workflows_org_id_fkey", "governance_custom_workflows", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_custom_workflows DROP CONSTRAINT IF EXISTS governance_custom_workflows_specific_user_id_fkey')
    op.create_foreign_key("governance_custom_workflows_specific_user_id_fkey", "governance_custom_workflows", "users", ["specific_user_id"], ["id"])
    op.execute('ALTER TABLE governance_dashboard_metrics DROP CONSTRAINT IF EXISTS governance_dashboard_metrics_created_by_fkey')
    op.create_foreign_key("governance_dashboard_metrics_created_by_fkey", "governance_dashboard_metrics", "users", ["created_by"], ["id"])
    op.execute('ALTER TABLE governance_dashboard_metrics DROP CONSTRAINT IF EXISTS governance_dashboard_metrics_org_id_fkey')
    op.create_foreign_key("governance_dashboard_metrics_org_id_fkey", "governance_dashboard_metrics", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_approver_fkey')
    op.create_foreign_key("governance_policies_approver_fkey", "governance_policies", "users", ["approver"], ["id"])
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_compliance_reviewer_fkey')
    op.create_foreign_key("governance_policies_compliance_reviewer_fkey", "governance_policies", "users", ["compliance_reviewer"], ["id"])
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_internal_reviewer_fkey')
    op.create_foreign_key("governance_policies_internal_reviewer_fkey", "governance_policies", "users", ["internal_reviewer"], ["id"])
    op.execute('ALTER TABLE governance_policies DROP CONSTRAINT IF EXISTS governance_policies_org_id_fkey')
    op.create_foreign_key("governance_policies_org_id_fkey", "governance_policies", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE governance_training_records DROP CONSTRAINT IF EXISTS governance_training_records_assigned_by_fkey')
    op.create_foreign_key("governance_training_records_assigned_by_fkey", "governance_training_records", "users", ["assigned_by"], ["id"])
    op.execute('ALTER TABLE governance_training_records DROP CONSTRAINT IF EXISTS governance_training_records_exemption_approved_by_fkey')
    op.create_foreign_key("governance_training_records_exemption_approved_by_fkey", "governance_training_records", "users", ["exemption_approved_by"], ["id"])
    op.execute('ALTER TABLE governance_training_records DROP CONSTRAINT IF EXISTS governance_training_records_org_id_fkey')
    op.create_foreign_key("governance_training_records_org_id_fkey", "governance_training_records", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE ifti_receipts DROP CONSTRAINT IF EXISTS ifti_receipts_org_id_fkey')
    op.create_foreign_key("ifti_receipts_org_id_fkey", "ifti_receipts", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE ifti_reports DROP CONSTRAINT IF EXISTS ifti_reports_org_id_fkey')
    op.create_foreign_key("ifti_reports_org_id_fkey", "ifti_reports", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE independent_reviews DROP CONSTRAINT IF EXISTS independent_reviews_org_id_fkey')
    op.create_foreign_key("independent_reviews_org_id_fkey", "independent_reviews", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_approval_questions DROP CONSTRAINT IF EXISTS org_approval_questions_org_id_fkey')
    op.create_foreign_key("org_approval_questions_org_id_fkey", "org_approval_questions", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_integrations DROP CONSTRAINT IF EXISTS org_integrations_org_id_fkey')
    op.create_foreign_key("org_integrations_org_id_fkey", "org_integrations", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_metrics_snapshots DROP CONSTRAINT IF EXISTS org_metrics_snapshots_org_id_fkey')
    op.create_foreign_key("org_metrics_snapshots_org_id_fkey", "org_metrics_snapshots", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_monitoring_configs DROP CONSTRAINT IF EXISTS org_monitoring_configs_org_id_fkey')
    op.create_foreign_key("org_monitoring_configs_org_id_fkey", "org_monitoring_configs", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_professional_checklist_templates DROP CONSTRAINT IF EXISTS org_professional_checklist_templates_org_id_fkey')
    op.create_foreign_key("org_professional_checklist_templates_org_id_fkey", "org_professional_checklist_templates", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_risk_factors DROP CONSTRAINT IF EXISTS org_risk_factors_org_id_fkey')
    op.create_foreign_key("org_risk_factors_org_id_fkey", "org_risk_factors", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_risk_matrix_versions DROP CONSTRAINT IF EXISTS org_risk_matrix_versions_org_id_fkey')
    op.create_foreign_key("org_risk_matrix_versions_org_id_fkey", "org_risk_matrix_versions", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE org_risk_profiles DROP CONSTRAINT IF EXISTS org_risk_profiles_org_id_fkey')
    op.create_foreign_key("org_risk_profiles_org_id_fkey", "org_risk_profiles", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE organisation_users DROP CONSTRAINT IF EXISTS organisation_users_organisation_id_fkey')
    op.create_foreign_key("organisation_users_organisation_id_fkey", "organisation_users", "organisations", ["organisation_id"], ["id"])
    op.execute('ALTER TABLE policies DROP CONSTRAINT IF EXISTS policies_org_id_fkey')
    op.create_foreign_key("policies_org_id_fkey", "policies", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE policy_attestations DROP CONSTRAINT IF EXISTS policy_attestations_org_id_fkey')
    op.create_foreign_key("policy_attestations_org_id_fkey", "policy_attestations", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE policy_review_reminders DROP CONSTRAINT IF EXISTS policy_review_reminders_org_id_fkey')
    op.create_foreign_key("policy_review_reminders_org_id_fkey", "policy_review_reminders", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE policy_versions DROP CONSTRAINT IF EXISTS policy_versions_org_id_fkey')
    op.create_foreign_key("policy_versions_org_id_fkey", "policy_versions", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE policy_workflow_events DROP CONSTRAINT IF EXISTS policy_workflow_events_org_id_fkey')
    op.create_foreign_key("policy_workflow_events_org_id_fkey", "policy_workflow_events", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE professional_assessments DROP CONSTRAINT IF EXISTS professional_assessments_org_id_fkey')
    op.create_foreign_key("professional_assessments_org_id_fkey", "professional_assessments", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE regulatory_recommendations DROP CONSTRAINT IF EXISTS regulatory_recommendations_org_id_fkey')
    op.create_foreign_key("regulatory_recommendations_org_id_fkey", "regulatory_recommendations", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE reporting_group_members DROP CONSTRAINT IF EXISTS reporting_group_members_org_id_fkey')
    op.create_foreign_key("reporting_group_members_org_id_fkey", "reporting_group_members", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE reporting_groups DROP CONSTRAINT IF EXISTS reporting_groups_holding_org_id_fkey')
    op.create_foreign_key("reporting_groups_holding_org_id_fkey", "reporting_groups", "organisations", ["holding_org_id"], ["id"])
    op.execute('ALTER TABLE risk_assessment_runs DROP CONSTRAINT IF EXISTS risk_assessment_runs_org_id_fkey')
    op.create_foreign_key("risk_assessment_runs_org_id_fkey", "risk_assessment_runs", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_assessments DROP CONSTRAINT IF EXISTS risk_assessments_org_id_fkey')
    op.create_foreign_key("risk_assessments_org_id_fkey", "risk_assessments", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_categories DROP CONSTRAINT IF EXISTS risk_categories_org_id_fkey')
    op.create_foreign_key("risk_categories_org_id_fkey", "risk_categories", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_controls DROP CONSTRAINT IF EXISTS risk_controls_org_id_fkey')
    op.create_foreign_key("risk_controls_org_id_fkey", "risk_controls", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_factor_scores DROP CONSTRAINT IF EXISTS risk_factor_scores_org_id_fkey')
    op.create_foreign_key("risk_factor_scores_org_id_fkey", "risk_factor_scores", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_factors DROP CONSTRAINT IF EXISTS risk_factors_org_id_fkey')
    op.create_foreign_key("risk_factors_org_id_fkey", "risk_factors", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_frameworks DROP CONSTRAINT IF EXISTS risk_frameworks_org_id_fkey')
    op.create_foreign_key("risk_frameworks_org_id_fkey", "risk_frameworks", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE risk_mitigations DROP CONSTRAINT IF EXISTS risk_mitigations_org_id_fkey')
    op.create_foreign_key("risk_mitigations_org_id_fkey", "risk_mitigations", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_organisation_id_fkey')
    op.create_foreign_key("roles_organisation_id_fkey", "roles", "organisations", ["organisation_id"], ["id"])
    op.execute('ALTER TABLE smr_reports DROP CONSTRAINT IF EXISTS smr_reports_org_id_fkey')
    op.create_foreign_key("smr_reports_org_id_fkey", "smr_reports", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_org_id_fkey')
    op.create_foreign_key("tasks_org_id_fkey", "tasks", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE training_assignments DROP CONSTRAINT IF EXISTS training_assignments_org_id_fkey')
    op.create_foreign_key("training_assignments_org_id_fkey", "training_assignments", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE training_courses DROP CONSTRAINT IF EXISTS training_courses_created_by_fkey')
    op.create_foreign_key("training_courses_created_by_fkey", "training_courses", "users", ["created_by"], ["id"])
    op.execute('ALTER TABLE training_courses DROP CONSTRAINT IF EXISTS training_courses_org_id_fkey')
    op.create_foreign_key("training_courses_org_id_fkey", "training_courses", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE training_records DROP CONSTRAINT IF EXISTS training_records_org_id_fkey')
    op.create_foreign_key("training_records_org_id_fkey", "training_records", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE training_trigger_logs DROP CONSTRAINT IF EXISTS training_trigger_logs_org_id_fkey')
    op.create_foreign_key("training_trigger_logs_org_id_fkey", "training_trigger_logs", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE training_trigger_rules DROP CONSTRAINT IF EXISTS training_trigger_rules_org_id_fkey')
    op.create_foreign_key("training_trigger_rules_org_id_fkey", "training_trigger_rules", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE ttr_reports DROP CONSTRAINT IF EXISTS ttr_reports_org_id_fkey')
    op.create_foreign_key("ttr_reports_org_id_fkey", "ttr_reports", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_org_id_fkey')
    op.create_foreign_key("users_org_id_fkey", "users", "organisations", ["org_id"], ["id"])
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS users_primary_organisation_id_fkey')
    op.create_foreign_key("users_primary_organisation_id_fkey", "users", "organisations", ["primary_organisation_id"], ["id"])
