"""Initial schema

Revision ID: ffafae2ef332
Revises: 
Create Date: 2026-06-11 05:43:30.811148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffafae2ef332'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='apikeystatus'), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=True)
    op.create_table('connector_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.Enum('greenid', 'sumsub', 'trulioo', 'jumio', 'onfido', 'complyadvantage', 'lexisnexis', 'dowjones', 'worldcheck', 'creditorwatch', 'equifax_au', 'loqate', 'google_maps', 'sendgrid', 'twilio', name='connectorprovider'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', name='connectorstatus'), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_credentials_credential_id'), 'connector_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_connector_credentials_id'), 'connector_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_connector_credentials_industry_id'), 'connector_credentials', ['industry_id'], unique=False)
    op.create_index(op.f('ix_connector_credentials_provider'), 'connector_credentials', ['provider'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('country_of_residence', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=100), nullable=False),
    sa.Column('id_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.Enum('banking', 'fintech', 'insurance', 'real_estate', 'cryptocurrency', 'other', name='industrytype'), nullable=False),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('source_of_funds', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'kyc_in_progress', 'kyc_approved', 'kyc_rejected', 'active', 'suspended', 'closed', name='customerstatus'), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_pep', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=60), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.Enum('kyc', 'aml', 'report', 'case', 'ecdd', 'contract', 'policy', 'correspondence', 'other', name='documentcategory'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='documentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('ifti_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ifti_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=60), nullable=True),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='iftidirection'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'submitted', name='iftistatus'), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('date_available', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('transfer_type', sa.String(length=20), nullable=True),
    sa.Column('property_description', sa.String(length=500), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('oc_full_name', sa.String(length=200), nullable=True),
    sa.Column('oc_other_name', sa.String(length=200), nullable=True),
    sa.Column('oc_dob', sa.Date(), nullable=True),
    sa.Column('oc_address', sa.String(length=300), nullable=True),
    sa.Column('oc_city', sa.String(length=100), nullable=True),
    sa.Column('oc_state', sa.String(length=50), nullable=True),
    sa.Column('oc_postcode', sa.String(length=20), nullable=True),
    sa.Column('oc_country', sa.String(length=100), nullable=True),
    sa.Column('oc_postal_address', sa.String(length=300), nullable=True),
    sa.Column('oc_postal_city', sa.String(length=100), nullable=True),
    sa.Column('oc_postal_state', sa.String(length=50), nullable=True),
    sa.Column('oc_postal_postcode', sa.String(length=20), nullable=True),
    sa.Column('oc_postal_country', sa.String(length=100), nullable=True),
    sa.Column('oc_phone', sa.String(length=50), nullable=True),
    sa.Column('oc_email', sa.String(length=200), nullable=True),
    sa.Column('oc_occupation', sa.String(length=200), nullable=True),
    sa.Column('oc_abn', sa.String(length=50), nullable=True),
    sa.Column('oc_customer_number', sa.String(length=100), nullable=True),
    sa.Column('oc_account_number', sa.String(length=100), nullable=True),
    sa.Column('oc_business_structure', sa.String(length=100), nullable=True),
    sa.Column('oc_id1_type', sa.String(length=100), nullable=True),
    sa.Column('oc_id1_type_other', sa.String(length=100), nullable=True),
    sa.Column('oc_id1_number', sa.String(length=100), nullable=True),
    sa.Column('oc_id1_issuer', sa.String(length=200), nullable=True),
    sa.Column('oc_id2_type', sa.String(length=100), nullable=True),
    sa.Column('oc_id2_type_other', sa.String(length=100), nullable=True),
    sa.Column('oc_id2_number', sa.String(length=100), nullable=True),
    sa.Column('oc_id2_issuer', sa.String(length=200), nullable=True),
    sa.Column('oc_electronic_source', sa.String(length=200), nullable=True),
    sa.Column('bc_full_name', sa.String(length=200), nullable=True),
    sa.Column('bc_dob', sa.Date(), nullable=True),
    sa.Column('bc_business_name', sa.String(length=200), nullable=True),
    sa.Column('bc_address', sa.String(length=300), nullable=True),
    sa.Column('bc_city', sa.String(length=100), nullable=True),
    sa.Column('bc_state', sa.String(length=50), nullable=True),
    sa.Column('bc_postcode', sa.String(length=20), nullable=True),
    sa.Column('bc_country', sa.String(length=100), nullable=True),
    sa.Column('bc_postal_address', sa.String(length=300), nullable=True),
    sa.Column('bc_postal_city', sa.String(length=100), nullable=True),
    sa.Column('bc_postal_state', sa.String(length=50), nullable=True),
    sa.Column('bc_postal_postcode', sa.String(length=20), nullable=True),
    sa.Column('bc_postal_country', sa.String(length=100), nullable=True),
    sa.Column('bc_phone', sa.String(length=50), nullable=True),
    sa.Column('bc_email', sa.String(length=200), nullable=True),
    sa.Column('bc_occupation', sa.String(length=200), nullable=True),
    sa.Column('bc_abn', sa.String(length=50), nullable=True),
    sa.Column('bc_business_structure', sa.String(length=100), nullable=True),
    sa.Column('bc_account_number', sa.String(length=100), nullable=True),
    sa.Column('bc_institution_name', sa.String(length=200), nullable=True),
    sa.Column('bc_institution_city', sa.String(length=100), nullable=True),
    sa.Column('bc_institution_country', sa.String(length=100), nullable=True),
    sa.Column('accept_id_number', sa.String(length=100), nullable=True),
    sa.Column('accept_full_name', sa.String(length=200), nullable=True),
    sa.Column('accept_address', sa.String(length=300), nullable=True),
    sa.Column('accept_city', sa.String(length=100), nullable=True),
    sa.Column('accept_state', sa.String(length=50), nullable=True),
    sa.Column('accept_postcode', sa.String(length=20), nullable=True),
    sa.Column('accept_country', sa.String(length=100), nullable=True),
    sa.Column('accept_postal_address', sa.String(length=300), nullable=True),
    sa.Column('accept_postal_city', sa.String(length=100), nullable=True),
    sa.Column('accept_postal_state', sa.String(length=50), nullable=True),
    sa.Column('accept_postal_postcode', sa.String(length=20), nullable=True),
    sa.Column('accept_postal_country', sa.String(length=100), nullable=True),
    sa.Column('accept_phone', sa.String(length=50), nullable=True),
    sa.Column('accept_email', sa.String(length=200), nullable=True),
    sa.Column('accept_occupation', sa.String(length=200), nullable=True),
    sa.Column('accept_business_structure', sa.String(length=100), nullable=True),
    sa.Column('accept_other_name', sa.String(length=200), nullable=True),
    sa.Column('accept_dob', sa.Date(), nullable=True),
    sa.Column('accept_abn', sa.String(length=50), nullable=True),
    sa.Column('is_accepting_money', sa.String(length=5), nullable=True),
    sa.Column('is_sending_instruction', sa.String(length=5), nullable=True),
    sa.Column('diff_accept_full_name', sa.String(length=200), nullable=True),
    sa.Column('diff_accept_address', sa.String(length=300), nullable=True),
    sa.Column('diff_accept_city', sa.String(length=100), nullable=True),
    sa.Column('diff_accept_state', sa.String(length=50), nullable=True),
    sa.Column('diff_accept_postcode', sa.String(length=20), nullable=True),
    sa.Column('diff_accept_country', sa.String(length=100), nullable=True),
    sa.Column('send_full_name', sa.String(length=200), nullable=True),
    sa.Column('send_other_name', sa.String(length=200), nullable=True),
    sa.Column('send_dob', sa.Date(), nullable=True),
    sa.Column('send_address', sa.String(length=300), nullable=True),
    sa.Column('send_city', sa.String(length=100), nullable=True),
    sa.Column('send_state', sa.String(length=50), nullable=True),
    sa.Column('send_postcode', sa.String(length=20), nullable=True),
    sa.Column('send_country', sa.String(length=100), nullable=True),
    sa.Column('send_postal_address', sa.String(length=300), nullable=True),
    sa.Column('send_postal_city', sa.String(length=100), nullable=True),
    sa.Column('send_postal_state', sa.String(length=50), nullable=True),
    sa.Column('send_postal_postcode', sa.String(length=20), nullable=True),
    sa.Column('send_postal_country', sa.String(length=100), nullable=True),
    sa.Column('send_phone', sa.String(length=50), nullable=True),
    sa.Column('send_email', sa.String(length=200), nullable=True),
    sa.Column('send_occupation', sa.String(length=200), nullable=True),
    sa.Column('send_abn', sa.String(length=50), nullable=True),
    sa.Column('send_business_structure', sa.String(length=100), nullable=True),
    sa.Column('recv_full_name', sa.String(length=200), nullable=True),
    sa.Column('recv_address', sa.String(length=300), nullable=True),
    sa.Column('recv_city', sa.String(length=100), nullable=True),
    sa.Column('recv_state', sa.String(length=50), nullable=True),
    sa.Column('recv_postcode', sa.String(length=20), nullable=True),
    sa.Column('recv_country', sa.String(length=100), nullable=True),
    sa.Column('is_distributing', sa.String(length=5), nullable=True),
    sa.Column('has_retail_outlet', sa.String(length=5), nullable=True),
    sa.Column('dist_full_name', sa.String(length=200), nullable=True),
    sa.Column('dist_address', sa.String(length=300), nullable=True),
    sa.Column('dist_city', sa.String(length=100), nullable=True),
    sa.Column('dist_state', sa.String(length=50), nullable=True),
    sa.Column('dist_postcode', sa.String(length=20), nullable=True),
    sa.Column('dist_country', sa.String(length=100), nullable=True),
    sa.Column('retail_id_number', sa.String(length=100), nullable=True),
    sa.Column('retail_full_name', sa.String(length=200), nullable=True),
    sa.Column('retail_address', sa.String(length=300), nullable=True),
    sa.Column('retail_city', sa.String(length=100), nullable=True),
    sa.Column('retail_state', sa.String(length=50), nullable=True),
    sa.Column('retail_postcode', sa.String(length=20), nullable=True),
    sa.Column('retail_country', sa.String(length=100), nullable=True),
    sa.Column('reason_for_transfer', sa.String(length=500), nullable=True),
    sa.Column('reporter_full_name', sa.String(length=200), nullable=True),
    sa.Column('reporter_job_title', sa.String(length=200), nullable=True),
    sa.Column('reporter_phone', sa.String(length=50), nullable=True),
    sa.Column('reporter_email', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifti_records_direction'), 'ifti_records', ['direction'], unique=False)
    op.create_index(op.f('ix_ifti_records_id'), 'ifti_records', ['id'], unique=False)
    op.create_index(op.f('ix_ifti_records_ifti_id'), 'ifti_records', ['ifti_id'], unique=True)
    op.create_index(op.f('ix_ifti_records_industry_id'), 'ifti_records', ['industry_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('csv', 'excel', 'manual', 'api', name='importsource'), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_batch_id'), 'import_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_table('industry_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('austrac_id', sa.String(length=100), nullable=True),
    sa.Column('pack_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_tenants_id'), 'industry_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_industry_tenants_industry_id'), 'industry_tenants', ['industry_id'], unique=True)
    op.create_index(op.f('ix_industry_tenants_tenant_id'), 'industry_tenants', ['tenant_id'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=60), nullable=False),
    sa.Column('subscription_id', sa.String(length=60), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('amount_aud', sa.Float(), nullable=False),
    sa.Column('tax_aud', sa.Float(), nullable=True),
    sa.Column('total_aud', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'paid', 'void', 'uncollectible', name='invoicestatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_hosted_url', sa.String(length=500), nullable=True),
    sa.Column('stripe_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_industry_id'), 'invoices', ['industry_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('legal_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=60), nullable=True),
    sa.Column('entity_scope', sa.Enum('customer', 'kyc_record', 'document', 'transaction', 'audit_log', 'report', name='entityscope'), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('held_by', sa.String(length=60), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_holds_active'), 'legal_holds', ['active'], unique=False)
    op.create_index(op.f('ix_legal_holds_entity_id'), 'legal_holds', ['entity_id'], unique=False)
    op.create_index(op.f('ix_legal_holds_hold_id'), 'legal_holds', ['hold_id'], unique=True)
    op.create_index(op.f('ix_legal_holds_id'), 'legal_holds', ['id'], unique=False)
    op.create_index(op.f('ix_legal_holds_industry_id'), 'legal_holds', ['industry_id'], unique=False)
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_id'), 'magic_link_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token'), 'magic_link_tokens', ['token'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notif_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('notif_type', sa.Enum('alert', 'report_due', 'report_approved', 'case_assigned', 'case_escalated', 'kyc_review', 'magic_link', 'system', 'ecdd_required', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='notificationpriority'), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('emailed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notif_id'), 'notifications', ['notif_id'], unique=True)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=False),
    sa.Column('customer_type', sa.Enum('individual', 'business', name='customertype'), nullable=True),
    sa.Column('applicant_name', sa.String(length=300), nullable=False),
    sa.Column('applicant_email', sa.String(length=300), nullable=False),
    sa.Column('applicant_phone', sa.String(length=50), nullable=True),
    sa.Column('applicant_company', sa.String(length=300), nullable=True),
    sa.Column('invite_token', sa.String(length=100), nullable=False),
    sa.Column('invite_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminders_sent', sa.Integer(), nullable=True),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('invited', 'opened', 'in_progress', 'documents_submitted', 'verification_pending', 'completed', 'expired', 'abandoned', 'rejected', name='sessionstatus'), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completion_pct', sa.Float(), nullable=True),
    sa.Column('documents_uploaded', sa.Integer(), nullable=True),
    sa.Column('collected_data', sa.JSON(), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('kyc_id', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('sanctions_match', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Enum('csv', 'excel', 'manual', 'api', name='importsource'), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sessions_id'), 'onboarding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_invite_token'), 'onboarding_sessions', ['invite_token'], unique=True)
    op.create_index(op.f('ix_onboarding_sessions_session_id'), 'onboarding_sessions', ['session_id'], unique=True)
    op.create_table('retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=60), nullable=True),
    sa.Column('entity_scope', sa.Enum('customer', 'kyc_record', 'document', 'transaction', 'audit_log', 'report', name='entityscope'), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_id'), 'retention_policies', ['id'], unique=False)
    op.create_index(op.f('ix_retention_policies_industry_id'), 'retention_policies', ['industry_id'], unique=False)
    op.create_index(op.f('ix_retention_policies_policy_id'), 'retention_policies', ['policy_id'], unique=True)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_events_event_id'), 'security_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('plan', sa.Enum('starter', 'professional', 'enterprise', 'vvip', 'free_trial', name='billingplan'), nullable=True),
    sa.Column('interval', sa.Enum('monthly', 'annual', name='billinginterval'), nullable=True),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'unpaid', 'incomplete', 'paused', name='subscriptionstatus'), nullable=True),
    sa.Column('base_price_aud', sa.Float(), nullable=True),
    sa.Column('custom_monthly_aud', sa.Float(), nullable=True),
    sa.Column('custom_annual_aud', sa.Float(), nullable=True),
    sa.Column('annual_discount_pct', sa.Float(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_industry_id'), 'subscriptions', ['industry_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('admin', 'mlro', 'analyst', 'compliance', 'viewer', name='userrole'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'pending', name='userstatus'), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=200), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=60), nullable=False),
    sa.Column('webhook_id', sa.String(length=60), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_delivery_id'), 'webhook_deliveries', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_webhook_deliveries_id'), 'webhook_deliveries', ['id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'failed', name='webhookstatus'), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_id'), 'webhook_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_webhook_id'), 'webhook_endpoints', ['webhook_id'], unique=True)
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('ttr', 'ifti_in', 'ifti_out', 'smr', 'sar', 'ctr', 'ecdd', name='reporttype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'submitted', 'acknowledged', 'rejected', name='reportstatus'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='reportpriority'), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('total_amount_flagged', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('transaction_ids', sa.JSON(), nullable=True),
    sa.Column('alert_ids', sa.JSON(), nullable=True),
    sa.Column('austrac_report_type', sa.String(length=50), nullable=True),
    sa.Column('reporting_entity', sa.String(length=300), nullable=True),
    sa.Column('reporting_entity_abn', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('prepared_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('mlro_sign_off', sa.Boolean(), nullable=True),
    sa.Column('submitted_to', sa.String(length=200), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_id'), 'compliance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_report_id'), 'compliance_reports', ['report_id'], unique=True)
    op.create_table('ecdd_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecdd_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('pep_status', sa.Integer(), nullable=True),
    sa.Column('adverse_media_found', sa.Integer(), nullable=True),
    sa.Column('adverse_media_details', sa.Text(), nullable=True),
    sa.Column('beneficial_owner_verified', sa.Integer(), nullable=True),
    sa.Column('beneficial_owner_details', sa.Text(), nullable=True),
    sa.Column('source_of_wealth_verified', sa.Integer(), nullable=True),
    sa.Column('source_of_wealth_details', sa.Text(), nullable=True),
    sa.Column('enhanced_risk_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecdd_records_ecdd_id'), 'ecdd_records', ['ecdd_id'], unique=True)
    op.create_index(op.f('ix_ecdd_records_id'), 'ecdd_records', ['id'], unique=False)
    op.create_table('kyc_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'document_submitted', 'under_review', 'identity_verified', 'approved', 'rejected', 'requires_ecdd', name='kycstatus'), nullable=True),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('document_score', sa.Float(), nullable=True),
    sa.Column('sanctions_checked', sa.Integer(), nullable=True),
    sa.Column('sanctions_match', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_records_id'), 'kyc_records', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_records_kyc_id'), 'kyc_records', ['kyc_id'], unique=True)
    op.create_table('monitoring_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('alert_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_cases_case_id'), 'monitoring_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_monitoring_cases_id'), 'monitoring_cases', ['id'], unique=False)
    op.create_table('onboarding_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_audit_logs_id'), 'onboarding_audit_logs', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('deposit', 'withdrawal', 'transfer', 'payment', 'exchange', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount_aud', sa.Float(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_account', sa.String(length=100), nullable=True),
    sa.Column('counterparty_country', sa.String(length=10), nullable=True),
    sa.Column('counterparty_bank', sa.String(length=200), nullable=True),
    sa.Column('is_cross_border', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'flagged', 'blocked', 'under_review', 'cleared', name='transactionstatus'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_suspicious', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('large_transaction', 'structuring', 'rapid_movement', 'high_risk_country', 'unusual_pattern', 'sanctions_match', 'velocity_breach', 'cross_border', 'pep_transaction', 'rule_triggered', name='alerttype'), nullable=True),
    sa.Column('alert_details', sa.Text(), nullable=True),
    sa.Column('rule_matches', sa.JSON(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_record_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('passport', 'national_id', 'driving_license', 'utility_bill', 'bank_statement', 'tax_return', 'selfie', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('extracted_name', sa.String(length=200), nullable=True),
    sa.Column('extracted_dob', sa.String(length=20), nullable=True),
    sa.Column('extracted_id_number', sa.String(length=100), nullable=True),
    sa.Column('extracted_expiry', sa.String(length=20), nullable=True),
    sa.Column('verification_result', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_record_id'], ['kyc_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_documents_id'), 'kyc_documents', ['id'], unique=False)
    op.create_table('transaction_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.String(length=100), nullable=True),
    sa.Column('alert_type', sa.Enum('large_transaction', 'structuring', 'rapid_movement', 'high_risk_country', 'unusual_pattern', 'sanctions_match', 'velocity_breach', 'cross_border', 'pep_transaction', 'rule_triggered', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'escalated', 'dismissed', 'resolved', 'reported', name='alertstatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('rule_name', sa.String(length=200), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('escalated_to', sa.String(length=200), nullable=True),
    sa.Column('is_resolved', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_alerts_alert_id'), 'transaction_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_transaction_alerts_id'), 'transaction_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_alerts_id'), table_name='transaction_alerts')
    op.drop_index(op.f('ix_transaction_alerts_alert_id'), table_name='transaction_alerts')
    op.drop_table('transaction_alerts')
    op.drop_index(op.f('ix_kyc_documents_id'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_onboarding_audit_logs_id'), table_name='onboarding_audit_logs')
    op.drop_table('onboarding_audit_logs')
    op.drop_index(op.f('ix_monitoring_cases_id'), table_name='monitoring_cases')
    op.drop_index(op.f('ix_monitoring_cases_case_id'), table_name='monitoring_cases')
    op.drop_table('monitoring_cases')
    op.drop_index(op.f('ix_kyc_records_kyc_id'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_id'), table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_index(op.f('ix_ecdd_records_id'), table_name='ecdd_records')
    op.drop_index(op.f('ix_ecdd_records_ecdd_id'), table_name='ecdd_records')
    op.drop_table('ecdd_records')
    op.drop_index(op.f('ix_compliance_reports_report_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_webhook_endpoints_webhook_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_webhook_deliveries_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_delivery_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_industry_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_retention_policies_policy_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_industry_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_id'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_onboarding_sessions_session_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_invite_token'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_id'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notif_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_magic_link_tokens_token'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_id'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_index(op.f('ix_legal_holds_industry_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_hold_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_entity_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_active'), table_name='legal_holds')
    op.drop_table('legal_holds')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_industry_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_industry_tenants_tenant_id'), table_name='industry_tenants')
    op.drop_index(op.f('ix_industry_tenants_industry_id'), table_name='industry_tenants')
    op.drop_index(op.f('ix_industry_tenants_id'), table_name='industry_tenants')
    op.drop_table('industry_tenants')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_batch_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_ifti_records_industry_id'), table_name='ifti_records')
    op.drop_index(op.f('ix_ifti_records_ifti_id'), table_name='ifti_records')
    op.drop_index(op.f('ix_ifti_records_id'), table_name='ifti_records')
    op.drop_index(op.f('ix_ifti_records_direction'), table_name='ifti_records')
    op.drop_table('ifti_records')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_connector_credentials_provider'), table_name='connector_credentials')
    op.drop_index(op.f('ix_connector_credentials_industry_id'), table_name='connector_credentials')
    op.drop_index(op.f('ix_connector_credentials_id'), table_name='connector_credentials')
    op.drop_index(op.f('ix_connector_credentials_credential_id'), table_name='connector_credentials')
    op.drop_table('connector_credentials')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
