"""
Regulatory Recommendation — decision support output linked to transactions, alerts, and cases.

The engine analyses transaction signals, customer risk, industry context, and alert
outputs to generate structured recommendations for compliance officers.

DESIGN PRINCIPLES:
  - Recommendations are NEVER auto-actioned — they require human review
  - Each recommendation carries a regulatory basis citation
  - All recommendations are auditable and immutable after generation
  - The platform makes no regulatory decisions; it surfaces considerations only

DISCLAIMER: Recommendations are compliance workflow guidance only.
The reporting entity bears sole responsibility for all regulatory decisions.
"""

import enum
from datetime import datetime
from typing import Optional
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, relationship

from app.db.database import Base


class RecommendationType(str, enum.Enum):
    # Regulatory reporting considerations
    consider_ifti = "consider_ifti"
    consider_ttr = "consider_ttr"
    consider_smr = "consider_smr"

    # Due diligence actions
    consider_edd = "consider_edd"
    request_source_of_funds = "request_source_of_funds"
    request_source_of_wealth = "request_source_of_wealth"

    # Customer management
    trigger_customer_review = "trigger_customer_review"
    escalate_to_mlro = "escalate_to_mlro"
    senior_approval_required = "senior_approval_required"

    # Monitoring
    enhanced_monitoring = "enhanced_monitoring"
    create_case = "create_case"

    # No action
    no_action_required = "no_action_required"


class RecommendationPriority(str, enum.Enum):
    low = "low"
    normal = "normal"
    high = "high"
    urgent = "urgent"


class RecommendationStatus(str, enum.Enum):
    pending = "pending"  # awaiting compliance officer review
    actioned = "actioned"  # officer has taken the suggested action
    dismissed = "dismissed"  # officer has reviewed and decided not to act
    superseded = "superseded"  # replaced by a newer recommendation


class RecommendationSource(str, enum.Enum):
    monitoring_engine = "monitoring_engine"  # generated by run_monitoring()
    manual = "manual"  # created by a compliance officer
    ai_assistant = "ai_assistant"  # future AI-generated (scaffold)


class RegulatoryRecommendation(Base):
    """
    Compliance decision support output — one row per recommended consideration.

    Generated automatically by the monitoring engine after alerts are produced.
    Linked to the originating transaction, alert, and/or case.

    IMMUTABLE after creation — status transitions only (pending → actioned/dismissed).
    """

    __tablename__ = "regulatory_recommendations"

    id: Mapped[str] = Column(
        String, primary_key=True, default=lambda: f"rec_{uuid4().hex[:12]}"
    )
    org_id: Mapped[str] = Column(
        String,
        ForeignKey("organisations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Links — at least one must be set
    transaction_id: Mapped[Optional[str]] = Column(
        String, ForeignKey("transactions.id"), nullable=True, index=True
    )
    alert_id: Mapped[Optional[str]] = Column(
        String, ForeignKey("transaction_alerts.id"), nullable=True, index=True
    )
    case_id: Mapped[Optional[str]] = Column(
        String, ForeignKey("cases.id"), nullable=True, index=True
    )
    customer_id: Mapped[Optional[str]] = Column(
        String, ForeignKey("customers.id"), nullable=True, index=True
    )

    # Classification
    recommendation_type: Mapped[RecommendationType] = Column(
        Enum(RecommendationType), nullable=False, index=True
    )
    priority: Mapped[Optional[RecommendationPriority]] = Column(
        Enum(RecommendationPriority, name="regulatory_recommendation_priority"),
        default=RecommendationPriority.normal,
    )
    source: Mapped[Optional[RecommendationSource]] = Column(
        Enum(RecommendationSource), default=RecommendationSource.monitoring_engine
    )

    # Content
    title: Mapped[str] = Column(String(500), nullable=False)
    recommendation_text: Mapped[str] = Column(
        Text, nullable=False
    )  # plain-English guidance
    rationale: Mapped[Optional[str]] = Column(Text)  # signals that triggered this
    regulatory_basis: Mapped[Optional[str]] = Column(
        String(500)
    )  # e.g. "AML/CTF Act 2006 s.45 — IFTI"

    # AI readiness scaffold — populated when source=ai_assistant
    is_ai_generated: Mapped[Optional[bool]] = Column(Boolean, default=False)
    ai_model: Mapped[Optional[str]] = Column(
        String(100)
    )  # model identifier (never auto-acted on)
    ai_reviewed_by: Mapped[Optional[str]] = Column(
        String
    )  # human who reviewed AI output

    # Workflow
    status: Mapped[RecommendationStatus] = Column(
        Enum(RecommendationStatus, name="regulatory_recommendation_status"),
        default=RecommendationStatus.pending,
        nullable=False,
        index=True,
    )
    actioned_by: Mapped[Optional[str]] = Column(String)  # user_id
    actioned_at: Mapped[Optional[datetime]] = Column(DateTime(timezone=True))
    action_taken: Mapped[Optional[str]] = Column(
        Text
    )  # officer's description of action
    dismissed_by: Mapped[Optional[str]] = Column(String)
    dismissed_at: Mapped[Optional[datetime]] = Column(DateTime(timezone=True))
    dismissed_reason: Mapped[Optional[str]] = Column(Text)

    created_at: Mapped[Optional[datetime]] = Column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    # No updated_at — status transitions are the only mutations allowed

    organisation = relationship("Organisation")

    __table_args__ = (
        Index("ix_rec_org_status", "org_id", "status"),
        Index("ix_rec_org_type", "org_id", "recommendation_type"),
        Index("ix_rec_transaction", "transaction_id", "status"),
    )
